"""install.sh against a temporary HOME and CODEX_HOME (AC-11, AC-12).

Every test builds its own scratch home; nothing here reads or writes the real ~/.claude or ~/.codex.
The retired v5.1 names are read from install.sh's own retire-v5 list rather than restated, so this
file adds no second copy of the set the repository's dangling-reference scan looks for.
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

INSTALL = Path(__file__).resolve().parents[1]
SCRIPT = INSTALL / "install.sh"
SKILLS = INSTALL / "skills"
PUBLISHED = {"execution-methodology", "agent-personas"}
GENERATED = "# GENERATED by agent-personas/scripts/sync_personas.py — edit the persona, not this."
GOAL_STOP = "skills/execution-methodology/scripts/goal.py stop-hook"
RUN_SH = "skills/execution-methodology/scripts/run.sh"


def retire_list() -> dict[str, list[str]]:
    text = SCRIPT.read_text(encoding="utf-8")
    block = text.split("# BEGIN retire-v5 list", 1)[1].split("# END retire-v5 list", 1)[0]
    return {k: v.split() for k, v in re.findall(r'^(RETIRED_\w+)="([^"]*)"', block, re.M)}


def declared_skills() -> set[str]:
    names = re.findall(r"^!/([A-Za-z0-9._-]+)$", (SKILLS / ".gitignore").read_text(), re.M)
    return {n for n in names if (SKILLS / n).is_dir()}


def pool() -> set[str]:
    """Spawnable persona names: every source except those marked `spawnable: no`."""
    return {p.stem for p in (SKILLS / "agent-personas" / "personas").glob("*.md")
            if not re.search(r"^spawnable:\s*no\s*$", p.read_text(encoding="utf-8"), re.M)}


def snapshot(root: Path) -> dict[str, str]:
    out = {}
    for p in sorted(root.rglob("*")):
        if p.is_file() and "__pycache__" not in p.parts:
            out[str(p.relative_to(root))] = hashlib.sha256(p.read_bytes()).hexdigest()
    return out


class InstallCase(unittest.TestCase):
    def setUp(self):
        self.home = Path(tempfile.mkdtemp(prefix="t6-home-")).resolve()
        self.addCleanup(shutil.rmtree, self.home, True)
        self.claude, self.codex = self.home / ".claude", self.home / ".codex"
        self.codex.mkdir()
        self.env = {**os.environ, "HOME": str(self.home), "CODEX_HOME": str(self.codex),
                    "PYTHONDONTWRITEBYTECODE": "1", "GIT_CONFIG_NOSYSTEM": "1",
                    "GIT_AUTHOR_NAME": "Fixture", "GIT_AUTHOR_EMAIL": "fixture@example.invalid",
                    "GIT_COMMITTER_NAME": "Fixture", "GIT_COMMITTER_EMAIL": "fixture@example.invalid"}
        for var in ("CLAUDE_PROJECT_DIR", "GOAL_ROLE"):
            self.env.pop(var, None)

    def install(self, *args, ok=True):
        r = subprocess.run(["bash", str(SCRIPT), *args], env=self.env, capture_output=True, text=True,
                           cwd=self.home)
        if ok:
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return r

    def write(self, path: Path, text: str) -> Path:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        return path

    def plant_v5(self) -> dict[str, Path]:
        """A machine as v5.1 left it, plus things that belong to nobody this installer knows."""
        r, planted = retire_list(), {}
        for s in r["RETIRED_SKILLS"]:
            for root in (self.claude, self.codex):
                planted[f"{root.name}/skill/{s}"] = self.write(root / "skills" / s / "SKILL.md", "v5.1\n")
        for p in r["RETIRED_PERSONAS"]:
            planted[f"claude/agent/{p}"] = self.write(self.claude / "agents" / f"{p}.md",
                                                      f"---\n{GENERATED}\nname: {p}\n---\nv5.1\n")
            planted[f"codex/agent/{p}"] = self.write(self.codex / "agents" / f"{p}.toml",
                                                     f'{GENERATED}\nname = "{p}"\n')
        for rel in r["RETIRED_SKILL_FILES"]:
            for root in (self.claude, self.codex):
                planted[f"{root.name}/{rel}"] = self.write(root / "skills" / rel, f"v5.1 {rel}\n")
        planted["unknown-in-skill"] = self.write(
            self.claude / "skills" / "execution-methodology" / "scripts" / "my_local_tool.py", "mine\n")
        planted["unknown-skill"] = self.write(self.claude / "skills" / "someone-elses" / "SKILL.md", "x\n")
        planted["unknown-agent"] = self.write(self.codex / "agents" / "my-own-worker.toml",
                                              f'{GENERATED}\nname = "my-own-worker"\n')
        planted["bundle"] = self.write(self.codex / "approved-runtimes" / "proj-v5.1" / "recovery.json", "{}\n")
        return planted


class InstallTest(InstallCase):
    def test_installs_exactly_the_published_skills_in_both_harnesses(self):
        self.assertEqual(declared_skills(), PUBLISHED)
        self.install()
        for root in (self.claude, self.codex):
            self.assertEqual({p.name for p in (root / "skills").iterdir()}, PUBLISHED, root)
            for s in PUBLISHED:
                self.assertTrue((root / "skills" / s / "SKILL.md").is_file(), (root, s))

    def test_registers_one_stop_hook_in_both_harnesses(self):
        self.install()
        settings = json.loads((self.claude / "settings.json").read_text())["hooks"]
        codex = json.loads((self.codex / "hooks.json").read_text())["hooks"]
        for hooks, root in ((settings, self.claude), (codex, self.codex)):
            stop = [h["command"] for e in hooks["Stop"] for h in e["hooks"]]
            self.assertEqual(stop.count(f"python3 {(root if hooks is codex else '~/.claude')}/{GOAL_STOP}"), 1, stop)
            self.assertNotIn("goal-session", json.dumps(hooks))
            self.assertTrue((root / GOAL_STOP.split()[0]).is_file())
            self.assertTrue(os.access(root / RUN_SH, os.X_OK), root / RUN_SH)
        # The registered Codex command is absolute and runs as written: outside any goal the Stop
        # hook allows silently.
        repo = self.home / "plain-repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q"], cwd=repo, env=self.env, check=True)
        r = subprocess.run(["bash", "-c", codex["Stop"][0]["hooks"][0]["command"]], cwd=repo, env=self.env,
                           input="{}", capture_output=True, text=True)
        self.assertEqual((r.returncode, r.stdout), (0, ""), r.stderr)

    def test_renders_the_persona_pool_for_both_harnesses(self):
        self.install()
        names = pool()
        self.assertTrue(names)
        self.assertEqual({p.stem for p in (self.claude / "agents").glob("*.md")}, names)
        self.assertEqual({p.stem for p in (self.codex / "agents").glob("*.toml")}, names)
        for n in names:
            self.assertIn(GENERATED, (self.claude / "agents" / f"{n}.md").read_text())

    def test_python_3_9_is_refused_because_the_floor_is_3_10(self):
        stub = self.home / "stub-bin"
        self.write(stub / "python3", '#!/bin/sh\n'
                                     'case "$2" in *"print("*) echo 3.9; exit 0;; esac\n'
                                     'exit 1\n')
        (stub / "python3").chmod(0o755)
        self.env["PATH"] = f"{stub}{os.pathsep}{self.env['PATH']}"
        r = self.install(ok=False)
        self.assertEqual(r.returncode, 1, r.stdout + r.stderr)
        self.assertIn("python3 3.9 found; 3.10 or newer is required", r.stderr)
        self.assertFalse((self.claude / "skills").exists(), "a refused install wrote skills")

    def test_dry_run_writes_nothing_and_a_second_install_changes_nothing(self):
        before = snapshot(self.home)
        out = self.install("--dry-run").stdout
        self.assertEqual(snapshot(self.home), before)
        self.assertIn("would install execution-methodology", out)
        self.install()
        first = snapshot(self.home)
        second = self.install().stdout
        self.assertEqual(snapshot(self.home), first)
        self.assertIn("0 added, 1 already present — settings.json unchanged", second)
        self.assertIn("0 added, 1 already present — hooks.json unchanged", second)
        self.assertFalse(list(self.home.rglob("*.bak-*")))

    def test_merge_keeps_existing_settings_and_hooks_in_place(self):
        self.write(self.claude / "settings.json", json.dumps(
            {"theme": "dark — mine", "hooks": {"Stop": [{"hooks": [{"type": "command", "command": "mine"}]}]}}))
        self.write(self.codex / "hooks.json", json.dumps(
            {"hooks": {"Stop": [{"hooks": [{"type": "command", "command": "user-stop"}]}]}}))
        self.install()
        settings = json.loads((self.claude / "settings.json").read_text())
        self.assertEqual(settings["theme"], "dark — mine")
        self.assertIn("dark — mine", (self.claude / "settings.json").read_text())
        self.assertEqual(settings["hooks"]["Stop"][0]["hooks"][0]["command"], "mine")
        codex = json.loads((self.codex / "hooks.json").read_text())["hooks"]["Stop"]
        # Appended, never reordered: Codex keys hook trust by event and index.
        self.assertEqual(codex[0]["hooks"][0]["command"], "user-stop")
        self.assertIn(GOAL_STOP, codex[1]["hooks"][0]["command"])
        self.assertEqual(len(list(self.claude.glob("settings.json.bak-*"))), 1)
        self.assertEqual(len(list(self.codex.glob("hooks.json.bak-*"))), 1)

    def test_malformed_settings_is_refused_and_left_alone(self):
        bad = self.write(self.claude / "settings.json", "{not json")
        r = self.install(ok=False)
        self.assertEqual(r.returncode, 1)
        self.assertIn("is not valid JSON", r.stdout)
        self.assertEqual(bad.read_text(), "{not json")


class RetireTest(InstallCase):
    def test_a_plain_install_removes_nothing(self):
        planted = self.plant_v5()
        contents = {k: p.read_bytes() for k, p in planted.items()}
        self.install()
        for key, path in planted.items():
            self.assertTrue(path.is_file(), key)
            self.assertEqual(path.read_bytes(), contents[key], key)

    def expected_deletions(self) -> set[Path]:
        r = retire_list()
        out = {root / "skills" / s for s in r["RETIRED_SKILLS"] for root in (self.claude, self.codex)}
        out |= {root / "skills" / f for f in r["RETIRED_SKILL_FILES"] for root in (self.claude, self.codex)}
        out |= {self.claude / "agents" / f"{p}.md" for p in r["RETIRED_PERSONAS"]}
        out |= {self.codex / "agents" / f"{p}.toml" for p in r["RETIRED_PERSONAS"]}
        return out

    def test_retire_v5_deletes_only_the_named_set_and_reports_the_rest(self):
        planted = self.plant_v5()
        # A hand-written agent that shares a retired name is not a render, so it is kept.
        hand = self.write(self.claude / "agents" / f"{retire_list()['RETIRED_PERSONAS'][0]}.md",
                          "---\nname: hand-written\n---\n")
        expected = self.expected_deletions() - {hand}

        dry = self.install("--retire-v5", "--dry-run").stdout
        would = {Path(line.split("would delete ", 1)[1]) for line in dry.splitlines()
                 if "would delete " in line}
        self.assertEqual(would, expected)
        self.assertTrue(all(p.exists() for p in planted.values()))

        out = self.install("--retire-v5").stdout
        deleted = {Path(line.split("deleted ", 1)[1]) for line in out.splitlines()
                   if line.strip().startswith("deleted ")}
        self.assertEqual(deleted, expected)
        for path in expected:
            self.assertFalse(path.exists(), path)
        for key in ("unknown-skill", "unknown-agent", "bundle", "unknown-in-skill"):
            self.assertTrue(planted[key].exists(), key)
        self.assertIn(f"left in place (not in the v5.1 set): {planted['unknown-in-skill']}", out)
        self.assertIn(f"left in place (not in the v5.1 set): {planted['unknown-skill'].parent}", out)
        self.assertIn(f"left in place (not in the v5.1 set): {planted['unknown-agent']}", out)
        self.assertIn("approved-runtimes", out)
        self.assertTrue(hand.exists())
        self.assertIn(f"kept {hand}", out)
        # The v6 install itself is intact afterwards.
        for root in (self.claude, self.codex):
            self.assertEqual({p.name for p in (root / "skills").iterdir()},
                             PUBLISHED | ({"someone-elses"} if root == self.claude else set()))


    def test_files_inside_an_installed_published_skill_survive_until_retire(self):
        # v5.1 left scripts, references and persona sources inside the skills v6 still publishes.
        self.install()
        listed = retire_list()["RETIRED_SKILL_FILES"]
        known = [next(f for f in listed if f.startswith(prefix)) for prefix in
                 ("execution-methodology/scripts/", "execution-methodology/references/",
                  "agent-personas/personas/")]
        planted = {rel: self.write(root / "skills" / rel, f"v5.1 {rel}\n")
                   for rel in known for root in (self.claude,)}
        unknown = self.write(self.codex / "skills" / "agent-personas" / "notes" / "mine.md", "mine\n")
        codex_known = self.write(self.codex / "skills" / known[0], "v5.1\n")

        dry = self.install("--dry-run").stdout
        for rel in known:
            self.assertIn(f"would keep {self.claude / 'skills' / rel} (not in this package)", dry)
        self.assertIn(f"would keep {unknown} (not in this package)", dry)
        self.install()
        for path in [*planted.values(), unknown, codex_known]:
            self.assertTrue(path.is_file(), path)
        # Vendored files are still current after the carry-forward.
        self.assertEqual((self.claude / "skills" / "execution-methodology" / "SKILL.md").read_bytes(),
                         (SKILLS / "execution-methodology" / "SKILL.md").read_bytes())

        dry = self.install("--retire-v5", "--dry-run").stdout
        self.assertEqual({Path(l.split("would delete ", 1)[1]) for l in dry.splitlines() if "would delete " in l},
                         {*planted.values(), codex_known})
        out = self.install("--retire-v5").stdout
        for path in [*planted.values(), codex_known]:
            self.assertFalse(path.exists(), path)
        self.assertTrue(unknown.is_file())
        self.assertIn(f"left in place (not in the v5.1 set): {unknown}", out)

    def test_installed_renderer_passes_check_beside_carried_v5_sources(self):
        # A project may run the installed renderer with `--repo <project> --check`; carried v5.1
        # sources must not make it fail before --retire-v5.
        self.install()
        sources = [f for f in retire_list()["RETIRED_SKILL_FILES"]
                   if f.startswith("agent-personas/personas/")]
        self.assertTrue(sources)
        for rel in sources:
            self.write(self.claude / "skills" / rel,
                       f"---\nname: {Path(rel).stem}\ndescription: v5.1\nwrites: yes\n---\nold\n")
        self.install()
        self.assertTrue(all((self.claude / "skills" / rel).is_file() for rel in sources))
        renderer = self.claude / "skills" / "agent-personas" / "scripts" / "sync_personas.py"
        project = self.home / "project"
        project.mkdir()
        for args in (["--check"], ["--repo", str(project), "--check"]):
            r = subprocess.run(["python3", str(renderer), *args], env=self.env, capture_output=True,
                               text=True)
            self.assertEqual(r.returncode, 0, (args, r.stdout + r.stderr))
            self.assertIn("retired persona source", r.stderr)

    def test_installed_renderer_and_repo_hooks_keep_v5_renders_until_retire(self):
        planted = self.plant_v5()   # v5.1 persona sources inside agent-personas, and their renders
        self.install()
        renders = [p for k, p in planted.items() if "/agent/" in k]
        self.assertEqual(len(renders), 2 * len(retire_list()["RETIRED_PERSONAS"]))
        renderer = self.claude / "skills" / "agent-personas" / "scripts" / "sync_personas.py"
        r = subprocess.run(["python3", str(renderer)], env=self.env, capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        repo = self.home / "repo"
        repo.mkdir()
        subprocess.run(["git", "init", "-q"], cwd=repo, env=self.env, check=True)
        hooks = self.claude / "skills" / "execution-methodology" / "scripts" / "git-hooks.sh"
        r = subprocess.run(["bash", str(hooks), str(repo)], env=self.env, capture_output=True,
                           text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        for path in renders:
            self.assertTrue(path.is_file(), path)

    def test_retire_is_skipped_when_an_install_step_failed(self):
        planted = self.plant_v5()
        self.write(self.claude / "settings.json", "{not json")
        r = self.install("--retire-v5", ok=False)
        self.assertEqual(r.returncode, 1)
        self.assertIn("SKIPPED: an install step above failed", r.stdout)
        self.assertTrue(all(p.exists() for p in planted.values()))

    def test_wrong_hook_shape_is_refused_without_a_traceback(self):
        bad = json.dumps({"hooks": {"Stop": {"not": "a list"}}})
        self.write(self.codex / "hooks.json", bad)
        r = self.install(ok=False)
        self.assertIn("is not in the expected hooks shape", r.stdout)
        self.assertNotIn("Traceback", r.stdout + r.stderr)
        self.assertEqual((self.codex / "hooks.json").read_text(), bad)


class GuardTest(InstallCase):
    def git(self, repo, *args, ok=True):
        r = subprocess.run(["git", *args], cwd=repo, env=self.env, capture_output=True, text=True)
        if ok:
            self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        return r

    def test_installed_pre_push_hook_blocks_a_planted_secret(self):
        self.install()
        repo, remote = self.home / "work", self.home / "remote.git"
        repo.mkdir()
        self.git(self.home, "init", "-q", "--bare", str(remote))
        self.git(repo, "init", "-q", "-b", "main")
        self.write(repo / "README.md", "fixture\n")
        self.git(repo, "add", "-A")
        self.git(repo, "commit", "-q", "-m", "init")
        self.git(repo, "remote", "add", "origin", str(remote))
        scripts = self.claude / "skills" / "execution-methodology" / "scripts"
        r = subprocess.run(["bash", str(scripts / "git-hooks.sh"), str(repo)], env=self.env,
                           capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn(str(scripts / "guard.py"), (repo / ".git" / "hooks" / "pre-push").read_text())
        # The installed pre-commit hook needs a private-name list; a synthetic one, never the real.
        names = self.write(self.home / "names.txt", "zarquon-widget\n")
        self.env["PD_PRIVATE_IDENTIFIERS"] = str(names)

        self.git(repo, "checkout", "-q", "-b", "clean")
        self.write(repo / "notes.txt", "nothing secret\n")
        self.git(repo, "add", "-A")
        self.git(repo, "commit", "-q", "-m", "clean")
        self.git(repo, "push", "-q", "origin", "clean")  # the control: the hook lets this through

        self.git(repo, "checkout", "-q", "-b", "leak")
        key = "AKIA" + "Q7RZM2XK4PLD9WTE"
        self.write(repo / "config.py", f'AWS_KEY = "{key}"\n')
        self.git(repo, "add", "-A")
        self.git(repo, "commit", "-q", "-m", "leak", "--no-verify")  # reach pre-push past pre-commit
        r = self.git(repo, "push", "origin", "leak", ok=False)
        self.assertNotEqual(r.returncode, 0, r.stdout + r.stderr)
        self.assertIn("guard BLOCKED", r.stdout + r.stderr)
        self.assertIn("AWS access key id", r.stdout + r.stderr)
        self.assertNotIn("leak", self.git(remote, "branch").stdout)


    def tree_scan_guard(self, files: dict[str, str], links: dict[str, str]):
        """Build a fixture repo (files committed with -f, then symlinks added), stage it the way
        verify.sh does, and return the guard's result over the scratch tree."""
        repo = self.home / f"fixture{len(list(self.home.glob('fixture*')))}"
        repo.mkdir()
        self.git(repo, "init", "-q", "-b", "main")
        self.write(repo / ".gitignore", "*.log\n")
        for rel, text in files.items():
            self.write(repo / rel, text)
        for rel, target in links.items():
            os.symlink(target, repo / rel)
        self.git(repo, "add", "-A", "-f")
        self.git(repo, "commit", "-q", "-m", "init")
        names = self.write(self.home / "names.txt", "zarquon-widget\n")
        env = {**self.env, "PD_PRIVATE_IDENTIFIERS": str(names)}
        scan = self.home / (repo.name + "-scan")
        r = subprocess.run(["python3", str(INSTALL / "tests" / "tree_scan.py"), str(repo), str(scan)],
                           env=env, capture_output=True, text=True)
        self.assertEqual(r.returncode, 0, r.stdout + r.stderr)
        guard = SKILLS / "execution-methodology" / "scripts" / "guard.py"
        return subprocess.run(["python3", str(guard), "--staged"], cwd=scan, env=env,
                              capture_output=True, text=True)

    def test_tree_guard_scans_ignored_tracked_files_and_symlinks(self):
        control = self.tree_scan_guard({"notes.txt": "nothing secret\n"}, {})
        self.assertEqual(control.returncode, 0, control.stdout + control.stderr)
        ignored = self.tree_scan_guard({"build.log": "see zarquon-widget\n"}, {})
        self.assertNotEqual(ignored.returncode, 0, "a tracked file an ignore rule matches went unscanned")
        link = self.tree_scan_guard({"notes.txt": "nothing secret\n"}, {"pointer": "/srv/zarquon-widget/data"})
        self.assertNotEqual(link.returncode, 0, "a symlink's link text went unscanned")


class LinkCheckTest(InstallCase):
    def links(self, *anchors: str) -> list[str]:
        import sys
        sys.path.insert(0, str(INSTALL / "tests"))
        from link_check import check_links
        repo = self.home / "docsrepo"
        self.write(repo / "docs" / "decisions" / "decisions.md",
                   "# Decisions\n\n## D17 — Zeta rule\n\n## D18: Other (thing)\n")
        self.write(repo / "AGENTS.md", "root\n")
        self.write(repo / "README.md", "".join(f"[x](docs/decisions/decisions.md#{a})\n" for a in anchors))
        subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
        subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
        return check_links(str(repo))

    def test_link_check_rejects_missing_decision_slug(self):
        self.assertEqual(self.links("d17", "d17--zeta-rule", "d18-other-thing"), [])
        bad = self.links("d17--nonexistent", "d99")
        self.assertEqual(len(bad), 2, bad)


class GoalStopHookTest(InstallCase):
    """The registered Stop command of each harness blocks a stop while a goal is not done."""

    def test_each_harness_blocks_an_unfinished_goal(self):
        import sys
        sys.path.insert(0, str(SKILLS / "execution-methodology" / "tests"))
        from fixtures.goal_fixture import Repo  # noqa: E402
        self.install()
        repo = Repo()
        self.addCleanup(repo.cleanup)
        for harness, file in (("claude", self.claude / "settings.json"), ("codex", self.codex / "hooks.json")):
            cmds = [h["command"] for e in json.loads(file.read_text())["hooks"]["Stop"] for h in e["hooks"]]
            r = subprocess.run(["bash", "-c", cmds[0]], cwd=repo.dir, env=self.env, capture_output=True,
                               text=True, input=json.dumps({"session_id": harness}))
            self.assertEqual(r.returncode, 0, r.stderr)
            self.assertEqual(json.loads(r.stdout)["decision"], "block", harness)


if __name__ == "__main__":
    unittest.main()
