#!/usr/bin/env python3
"""The pages under docs/: `lint [ROOT]`, `index [ROOT]`, `reads <Tn> [--goal <id>]`, `pointers [ROOT]
[--check]`, `stale [ROOT]`.

lint: every tracked docs/**/*.md but docs/README.md, docs/goals/** and AGENTS.md starts with summary (<=120
words), read-when, covers and last-verified, the table in docs/README.md is `index`'s output, and
`pointers --check` finds nothing.
reads: each entry of the task's reads: line as path:start-end, path, or term: <word>; the plan is
found the way goal.py finds it.
pointers: for each page with a non-empty covers, the generated .claude/rules/<page-slug>.md (the
path under docs/ with each segment slugged, joined by `--`; two pages naming one file are refused) and the
block between the pointer markers in the nearest AGENTS.md at or above each glob's literal
directory (a new AGENTS.md there when none exists). An unmarked file is reported and never written;
pointers whose page dropped covers are removed; a destination resolving outside ROOT is refused.
--check writes nothing and reports each file a regeneration would change.
stale: a page whose covered paths' last commit is on a day after last-verified, or on that day and
later than the page's own last commit (committer timestamps). Only commits are seen: an uncommitted
change does not make a page stale.
Exit codes: 0 clean, 1 findings, 2 could not run.
"""
from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from goal import PlanError, find_ctx, git, parse_plan  # noqa: E402

KEYS = ("summary", "read-when", "covers", "last-verified")
HEADER = ["| Page | Read when |", "|---|---|"]
MARK = "<!-- generated by docs.py pointers; edit the page's frontmatter instead -->"
START, END = "<!-- docs.py pointers -->", "<!-- /docs.py pointers -->"

def slug(heading: str) -> str:
    """A GitHub heading anchor: lowercased, markup and punctuation dropped, each space a '-'."""
    text = re.sub(r"[`*_~]", "", heading.strip().lower())
    return re.sub(r"[^\w\- ]", "", text).replace(" ", "-")

def fenced(lines):
    """(n, line, inside) per line, n from 1; inside is true within a ``` or ~~~ fence and on its opening line."""
    fence = None
    for n, line in enumerate(lines, 1):
        s = line.lstrip()
        fence = (None if s.startswith(fence) else fence) if fence else (s[:3] if s.startswith(("```", "~~~")) else None)
        yield n, line, bool(fence)

def headings(lines):
    """[(n, level, text)] for every Markdown heading outside a code fence."""
    return [(n, len(h.group(1)), h.group(2)) for n, line, inside in fenced(lines)
            if not inside and (h := re.match(r"(#{1,6})\s+(.*?)\s*#*$", line))]

def anchors(heads):
    """Each heading's GitHub anchor; a repeated slug gains -1, -2 the way GitHub suffixes it."""
    slugs, seen = [], {}
    for _n, _l, text in heads:
        s = slug(text); slugs.append(f"{s}-{seen[s]}" if s in seen else s); seen[s] = seen.get(s, 0) + 1
    return slugs

def relative(glob):
    return isinstance(glob, str) and glob and not glob.startswith("/") and ".." not in glob.split("/")

def covered(meta):
    """The page's repository-relative covers globs."""
    return [g for g in meta["covers"] if relative(g)] if isinstance(meta.get("covers"), list) else []

def pages(root):
    """Tracked docs/**/*.md but the index, the goals and any AGENTS.md (a pointer target, not a page)."""
    files = git(root, "ls-files", "-z", "--", "docs/*.md").split("\0")
    return sorted(f for f in files if f.endswith(".md") and f != "docs/README.md"
                  and not f.startswith("docs/goals/") and not f.endswith("/AGENTS.md"))

def frontmatter(root, page):
    return parse_plan((Path(root) / page).read_text(encoding="utf-8"))

def index(root):
    whens = {p: frontmatter(root, p)["meta"].get("read-when") for p in pages(root)}
    return HEADER + [f"| [{p[5:]}]({p[5:]}) | {w if isinstance(w, str) else ''} |" for p, w in whens.items()]

def lint(root):
    errs = []
    for page in pages(root):
        parsed = frontmatter(root, page)  # parse_plan's errors that start "line " are the frontmatter's
        meta = parsed["meta"]
        errs += [f"{page}: frontmatter {e}" for e in parsed["errors"] if e.startswith("line ")]
        for key in KEYS:
            if meta.get(key) in (None, {}, ""):
                errs.append(f"{page}: no {key}")
            elif not isinstance(meta[key], list if key == "covers" else str):
                errs.append(f"{page}: {key} is not {'a list' if key == 'covers' else 'one line'}")
        summary, date = meta.get("summary"), meta.get("last-verified")
        if isinstance(summary, str) and len(summary.split()) > 120:
            errs.append(f"{page}: summary is {len(summary.split())} words, over 120")
        if isinstance(date, str) and date:
            try:
                dt.date.fromisoformat(date if re.fullmatch(r"\d{4}-\d{2}-\d{2}", date) else "not a date")
            except ValueError:
                errs.append(f"{page}: last-verified {date!r} is not a YYYY-MM-DD date")
        covers = meta["covers"] if isinstance(meta.get("covers"), list) else []
        errs += [f"{page}: covers entry {c!r} is not repository-relative" for c in covers if not relative(c)]
    readme = Path(root) / "docs" / "README.md"
    lines = [l.strip() for l in readme.read_text(encoding="utf-8").splitlines()] if readme.is_file() else []
    if HEADER[0] not in lines:
        return errs + [f"docs/README.md: no index table (header {HEADER[0]})"] + pointers(root, check=True)
    start, want = lines.index(HEADER[0]), index(root)
    have = lines[start:next((k for k in range(start, len(lines)) if not lines[k].startswith("|")), len(lines))]
    if have != want:  # the table runs from its header row to the last row; prose around it is free
        errs += ([f"docs/README.md: index lacks {r}" for r in want if r not in have]
                 + [f"docs/README.md: index has extra {r}" for r in have if r not in want]
                 or ["docs/README.md: index rows out of order; print them with docs.py index"])
    return errs + pointers(root, check=True)

def entry(root, page, base):
    """Lines pointing from a file in directory base at page: its link and read-when, then its H2 anchors."""
    when = frontmatter(root, page)["meta"].get("read-when")
    heads = headings((root / page).read_text(encoding="utf-8").splitlines())
    link = Path(os.path.relpath(root / page, root / base)).as_posix()
    return ([f"[{page}]({link}), read when: {when if isinstance(when, str) else ''}"]
            + [f"- {page}#{a}" for (_n, level, _t), a in zip(heads, anchors(heads)) if level == 2])

def agents_md(root, glob):
    """The nearest AGENTS.md at or above the glob's longest literal directory, else a new one there."""
    literal = re.split(r"[*?[]", glob)[0]
    base = glob if literal == glob and (root / glob).is_dir() else literal.rpartition("/")[0]
    parts = [s for s in base.split("/") if s]
    found = (k for k in range(len(parts), -1, -1) if os.path.lexists(root / "/".join(parts[:k] + ["AGENTS.md"])))
    return "/".join(parts[:next(found, len(parts))] + ["AGENTS.md"])

def generated(text):
    lines = text.splitlines()
    return lines[:1] == ["---"] and "---" in lines[1:] and lines[lines.index("---", 1) + 1:][:1] == [MARK]

def inside(root, path):
    return Path(os.path.realpath(path)).is_relative_to(root)

def pointers(root, check=False):
    """The findings; unless check, writes or removes each pointer file that differs and prints its path."""
    root, errs, want, blocks = Path(os.path.realpath(root)), [], {}, {}
    named = {}
    for page in pages(root):
        if globs := covered(frontmatter(root, page)["meta"]):
            rule = f".claude/rules/{'--'.join(slug(s) for s in page[5:-3].split('/'))}.md"
            named.setdefault(rule, []).append(page)  # paths: as a JSON flow list: YAML reads it, a bare * would break
            want[rule] = (f"---\npaths: {json.dumps(globs)}\n---\n{MARK}\n"
                          + "".join(f"{l}\n" for l in entry(root, page, ".claude/rules")))
            for glob in globs:
                blocks.setdefault(agents_md(root, glob), set()).add(page)
    for rule, named_by in named.items():
        if len(named_by) > 1:  # two pages would share one rule file: neither is written
            errs.append(f"{rule}: named by both {' and '.join(named_by)}")
            del want[rule]
    rules = root / ".claude" / "rules"
    for f in sorted(rules.glob("*.md")) if rules.is_dir() else []:
        if f".claude/rules/{f.name}" not in want and f.is_file() and generated(f.read_bytes().decode("utf-8")):
            want[f".claude/rules/{f.name}"] = None
    listed = git(root, "ls-files", "-z", "--cached", "--others", "--exclude-standard", "--", ":(glob)**/AGENTS.md")
    for rel in filter(None, listed.split("\0")):
        p = root / rel  # a marked AGENTS.md no page maps to keeps its markers around an empty block
        if rel not in blocks and inside(root, p) and p.is_file() and START in p.read_bytes().decode("utf-8"):
            blocks[rel] = set()
    for rel in sorted(set(want) | set(blocks)):
        p = root / rel
        if not inside(root, p):
            errs.append(f"{rel}: resolves outside the repository")
            continue
        have, new = p.read_bytes().decode("utf-8") if p.is_file() else None, want.get(rel)
        start = -1 if have is None else have.find(START)
        if rel in blocks and have is not None and (start < 0 or have.find(END, start) < 0) or (
                rel not in blocks and have is not None and new is not None and not generated(have)):
            errs.append(f"{rel}: no pointer markers")
            continue
        if rel in blocks:
            body = "".join(f"{l}\n" for k, page in enumerate(sorted(blocks[rel]))
                           for l in ([""] if k else []) + entry(root, page, rel.rpartition("/")[0]))
            new = (f"{START}\n{body}{END}\n" if have is None
                   else have[:start + len(START)] + f"\n{body}" + have[have.find(END, start):])
        if have == new:
            continue
        if check:
            errs.append(f"{rel}: would change")
            continue
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(new.encode("utf-8")) if new is not None else p.unlink()
        print(f"{rel}: {'written' if new is not None else 'removed'}")
    return errs

def stale(root):
    """One line per page whose covered paths were committed after its last-verified day."""
    found = []
    for page in pages(root):
        globs, day = covered(meta := frontmatter(root, page)["meta"]), meta.get("last-verified")
        if not globs or not isinstance(day, str):
            continue
        last = git(root, "log", "-1", "--format=%cI", "--", *(f":(glob){g}" for g in globs))
        own = git(root, "log", "-1", "--format=%cI", "--", page)
        later = last and own and dt.datetime.fromisoformat(last.replace("Z", "+00:00")) > dt.datetime.fromisoformat(
            own.replace("Z", "+00:00"))  # git may print UTC as Z
        if last and (last[:10] > day or last[:10] == day and later):
            found.append(f"{page}: {last} after last-verified {day}")
    return found

def resolve(root, entry):
    """(ok, line) for one reads: entry: a term, a whole file, or a file's section by anchor."""
    path, hashed, anchor = entry.partition("#")
    target = Path(root) / path
    if not hashed and "/" not in entry and "." not in entry and not target.exists():
        return True, f"term: {entry}"
    if not (target.is_file() if hashed else target.exists()):
        return False, f"{entry}: no such file"
    if not hashed:
        return True, path
    lines = target.read_text(encoding="utf-8").splitlines()
    heads, number = headings(lines), re.fullmatch(r"d(\d+)", anchor, re.I)
    slugs = anchors(heads)  # GitHub suffixes a repeated slug: examples, examples-1, examples-2
    for k, (n, level, text) in enumerate(heads):  # the section ends before a heading of its level or higher
        if slugs[k] == anchor.lower() or (number and re.match(rf"D{number[1]}\b", text, re.I)):
            return True, f"{path}:{n}-{next((m - 1 for m, lv, _t in heads[k + 1:] if lv <= level), len(lines))}"
    return False, f"{entry}: no heading matches #{anchor}"

def cmd_reads(a):
    ctx = find_ctx(goal=a.goal)
    if (task := ctx.plan["tasks"].get(a.task)) is None:
        raise PlanError(f"{ctx.plan_rel} has no task {a.task}")
    results = [resolve(ctx.root, e) for e in task["reads"]]
    print("\n".join(line if ok else f"error: {line}" for ok, line in results))
    return 0 if all(ok for ok, _l in results) else 1

def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="action", required=True)
    parsers = {name: sub.add_parser(name) for name in ("lint", "index", "pointers", "stale")}
    [p.add_argument("root", nargs="?", default=".") for p in parsers.values()]
    parsers["pointers"].add_argument("--check", action="store_true")
    reads = sub.add_parser("reads")
    reads.add_argument("task")
    reads.add_argument("--goal")
    a = ap.parse_args(argv)
    try:
        if a.action in ("reads", "index"):
            return cmd_reads(a) if a.action == "reads" else print("\n".join(index(a.root))) or 0
        errs = {"lint": lint, "stale": stale}.get(a.action, lambda root: pointers(root, a.check))(a.root)
        verdict = f"{len(errs)} stale" if a.action == "stale" else f"FAIL ({len(errs)})"
        print("".join(f"{e}\n" for e in errs) + f"docs.py {a.action}: {verdict if errs else 'PASS'}")
        return 1 if errs else 0
    except (PlanError, RuntimeError, OSError, ValueError) as exc:
        print(f"docs.py: {exc}", file=sys.stderr)
        return 2

if __name__ == "__main__":
    sys.exit(main())
