#!/usr/bin/env python3
"""Render the execution methodology into a repository so both harnesses read the same rules.

The methodology is authored once, harness-neutral, in `methodology.md`. This renders it to:

  <repo>/docs/agents/execution/methodology.md   the in-repo copy Claude Code and Codex both read

Rendering is not a convenience. Codex CLI has no Skill tool, so a skill living in `~/.claude/skills`
is invisible to it; in-repo markdown is the only channel both harnesses reliably read. Keeping the
copy generated rather than hand-maintained is what stops three repositories from slowly running
three different methodologies.

Per-project use: an overlay at `<repo>/docs/agents/execution/overlay.md` is appended under a
"Repository-specific execution rules" heading. That is where a repo binds the abstract stages to its
real commands — its context script, its area gates, its ledger path. The overlay is authored by the
repo and never generated.

Adoption is staggered and deliberate. Repositories come under this methodology one at a time, by
someone running the render on purpose; nothing here ever adopts a repository on its own. Until a
repository has adopted it, `--adoption-check` says so at every session start — see the adoption
section below.

Usage:
  sync_methodology.py --repo PATH                    # render into that repository
  sync_methodology.py --repo PATH --check            # exit 1 if the rendered copy is stale (gates)
  sync_methodology.py --repo PATH --adoption-check   # report adoption state; ALWAYS exits 0
  sync_methodology.py --list                         # show the source, version, and rendered date
  sync_methodology.py --repo PATH --list             # ... plus that repo's target and overlay state
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import date, datetime, timezone
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
SOURCE = SKILL / "methodology.md"

# Bump when the methodology's rules change. MAJOR for a change that invalidates how a repo already
# works — a stage removed, a gate moved, an artifact renamed. MINOR for additive clarification.
# Rendered copies carry this stamp so a repo running an older methodology can be detected instead of
# silently drifting. validate_disclosure.py reads this constant to decide WARN versus ERROR.
METHODOLOGY_VERSION = "1.4"

TARGET_REL = Path("docs") / "agents" / "execution" / "methodology.md"
OVERLAY_REL = Path("docs") / "agents" / "execution" / "overlay.md"
OVERLAY_HEADING = "## Repository-specific execution rules"

# The repository's own authored route index. Rendering into docs/agents/execution/methodology.md
# without a route pointing at it produces a file nothing reaches — invisible, and invisibly so.
# This script never writes README.md itself; sync_personas.py sets the precedent of preserving
# unmanaged files rather than clobbering them, and the route index is squarely the repo's own work.
README_REL = Path("docs") / "agents" / "README.md"

# A markdown inline link: [text](target) or [text](target "title"). Reference-style links
# (`[text][ref]`) are not matched — the existing route row uses inline form, and that is the only
# form this checks for.
LINK_RE = re.compile(r"\[[^\]]*\]\(([^)\s]+)(?:\s+\"[^\"]*\")?\)")

# The exact row shape to paste, matching docs/agents/README.md:48's relative-link form
# (`[execution/methodology.md](execution/methodology.md)`, relative to docs/agents/). The middle
# columns are placeholders — what a lane inspects and gates on is per-repository, but the link form
# is not.
ROUTE_ROW = (
    "| Spec, design, plan, or executing a plan | "
    "[execution/methodology.md](execution/methodology.md) — the pipeline, its gates, the task "
    "card, the ledger contract | <the active plan and its workspace> | <this repo's gate for it> |"
)

# The banner names the skill-relative source, never an absolute home path: an absolute path would
# differ between machines and every check on a second machine would report drift.
GENERATED = ("<!-- GENERATED by execution-methodology/scripts/sync_methodology.py from "
             "execution-methodology/methodology.md — do not hand-edit this file; "
             "edit the methodology, or this repo's docs/agents/execution/overlay.md. -->")

# Exactly the single-line JSON comment spelling validate_disclosure.py already parses for personas.
MARKER_RE = re.compile(r"<!--\s*execution-methodology:\s*(\{[^\r\n]*\})\s*-->", re.IGNORECASE)

# Anything that *claims* to be one of our markers, well-formed or not. Counting only well-formed
# markers would let a typo read as "no decision recorded", which is the one reading a deferral must
# never silently collapse into. Mirrors PERSONA_MARKER / PERSONA_MARKER_ANY in validate_disclosure.
MARKER_ANY_RE = re.compile(r"<!--\s*execution-methodology:.*?-->", re.IGNORECASE | re.DOTALL)

# The deferral decision, recorded in the repository's own routed index — docs/agents/README.md, the
# first file every agent in every harness reads. It is the same file, and the same single-line JSON
# comment shape, that carries the `agent-personas` base-only decision; a repository records "I chose
# not to adopt this, for this reason, on this date" exactly where it records "I chose the base
# persona pool, for this reason". A decision filed anywhere else is a decision nobody reads.
#
# Strictness follows that precedent exactly: one marker, valid single-line JSON, and a non-empty
# reason. An empty reason is not a decision, it is silence with punctuation, and it is treated as
# unadopted. The date is this file's own addition — it makes a deferral visibly age instead of
# quietly becoming permanent.
DEFER_MODE = "deferred"
DEFERRAL_EXAMPLE = ('<!-- execution-methodology: {"mode":"deferred",'
                    '"reason":"<one line: why not yet>","date":"YYYY-MM-DD"} -->')

FENCE_RE = re.compile(r"^\s{0,3}(?:```|~~~)")
INLINE_CODE_RE = re.compile(r"`[^`\n]*`")


class MethodologyError(Exception):
    pass


def strip_code(text: str) -> str:
    """Drop fenced and inline code so a documented example is never read as a decision.

    A repository that documents the marker — in its own route index, under a fence — must not
    thereby be reported as having deferred. validate_disclosure.py strips code before reading the
    persona marker for the same reason.
    """
    out: list[str] = []
    fenced = False
    for line in text.splitlines():
        if FENCE_RE.match(line):
            fenced = not fenced
            continue
        if not fenced:
            out.append(INLINE_CODE_RE.sub("", line))
    return "\n".join(out)


def source_text() -> str:
    if not SOURCE.is_file():
        raise MethodologyError(f"no methodology source at {SOURCE}")
    text = SOURCE.read_text(encoding="utf-8").strip()
    if not text:
        raise MethodologyError(f"{SOURCE} is empty")
    return text


def rendered_date(explicit: str | None = None) -> str:
    """The date stamped into the marker.

    Taken from the source's mtime, not from today. A date read at check time would differ from the
    date written at render time on the very next day, and `--check` would report drift every morning
    in every repository until someone muted it.
    """
    if explicit:
        if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", explicit):
            raise MethodologyError(f"--rendered must be YYYY-MM-DD, got {explicit!r}")
        return explicit
    return datetime.fromtimestamp(SOURCE.stat().st_mtime, tz=timezone.utc).date().isoformat()


def marker(date: str) -> str:
    payload = json.dumps({"v": METHODOLOGY_VERSION, "rendered": date}, separators=(",", ":"))
    return f"<!-- execution-methodology: {payload} -->"


def render(body: str, date: str, overlay: str | None) -> str:
    parts = [GENERATED, marker(date), "", body.rstrip()]
    if overlay is not None:
        parts += ["", OVERLAY_HEADING, "", overlay.strip()]
    return "\n".join(parts) + "\n"


def read_overlay(repo: Path) -> str | None:
    """An overlay that exists but says nothing is a mistake, not an empty section."""
    path = repo / OVERLAY_REL
    if not path.is_file():
        return None
    text = path.read_text(encoding="utf-8", errors="replace").strip()
    if not text:
        raise MethodologyError(f"{OVERLAY_REL.as_posix()} exists but is empty")
    return text


def is_ours(text: str) -> bool:
    """Only files this script generated may be overwritten.

    A hand-written docs/agents/execution/methodology.md is somebody's work. Personas preserve unmanaged files in
    the same situation and let the check report them, rather than deleting or clobbering them.
    """
    return GENERATED in text


def route_status(repo: Path) -> tuple[bool, str]:
    """Whether `docs/agents/README.md` links to the rendered methodology.

    Links are resolved relative to `docs/agents/`, matching the existing row's
    `[execution/methodology.md](execution/methodology.md)` form. Returns (True, "") when routed;
    otherwise (False, <reason>) — either the README does not exist at all, or none of its links
    resolve to the rendered target.
    """
    readme = repo / README_REL
    if not readme.is_file():
        return False, f"{README_REL.as_posix()} does not exist — this repository has no route index"

    text = readme.read_text(encoding="utf-8", errors="replace")
    base = (repo / "docs" / "agents").resolve()
    target = (repo / TARGET_REL).resolve()
    for m in LINK_RE.finditer(text):
        link = m.group(1).split("#", 1)[0].strip()
        if not link or link.startswith(("http://", "https://", "mailto:")):
            continue
        try:
            resolved = (base / link).resolve()
        except (OSError, ValueError):
            continue
        if resolved == target:
            return True, ""
    return False, f"no link in {README_REL.as_posix()} resolves to {TARGET_REL.as_posix()}"


def print_route_advice(detail: str) -> None:
    print(f"    {detail}")
    print(f"  paste this row into {README_REL.as_posix()} (create the file if it does not exist):")
    print(f"    {ROUTE_ROW}")


def sync(repo: Path, check: bool, explicit_date: str | None) -> int:
    try:
        body = source_text()
        date = rendered_date(explicit_date)
        overlay = read_overlay(repo)
    except MethodologyError as e:
        print(e, file=sys.stderr)
        return 2

    target = repo / TARGET_REL
    expected = render(body, date, overlay)
    current = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else None

    print(f"execution methodology v{METHODOLOGY_VERSION} (source rendered {date})"
          f" -> {repo.name}/{TARGET_REL.as_posix()}"
          + (f", overlay {OVERLAY_REL.as_posix()}" if overlay is not None else ""))

    if current is not None and not is_ours(current):
        where = f"{target} (unmanaged — not generated by this script)"
        if check:
            print("  STALE — the rendered methodology does not match its source:")
            print(f"    {where}")
            print(f"  run: sync_methodology.py --repo {repo}")
            return 1
        print(f"  refusing to overwrite {where}", file=sys.stderr)
        print("  move it aside, then re-run", file=sys.stderr)
        return 2

    if current == expected:
        if check:
            routed, detail = route_status(repo)
            if not routed:
                print("  ERROR — nothing routes to the rendered methodology:")
                print_route_advice(detail)
                return 1
            print("  in sync")
            return 0
        print("  already up to date")
        routed, detail = route_status(repo)
        if not routed:
            print("  WARNING — rendered, but nothing routes to it:")
            print_route_advice(detail)
        return 0

    if check:
        reason = "missing" if current is None else "stale or hand-edited"
        print("  STALE — the rendered methodology does not match its source:")
        print(f"    {target} ({reason})")
        print(f"  run: sync_methodology.py --repo {repo}")
        return 1

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(expected, encoding="utf-8")
    print(f"  wrote   {target}")
    routed, detail = route_status(repo)
    if not routed:
        print("  WARNING — rendered, but nothing routes to it:")
        print_route_advice(detail)
    return 0


def read_deferral(repo: Path) -> tuple[dict | None, str | None]:
    """The repository's deliberate-deferral decision, if it recorded a valid one.

    Returns (decision, problem). Exactly one of them is ever non-None:
      (None, None)        nothing recorded — the repository has simply not decided
      (None, "<why>")     something is recorded but does not count as a decision
      ({...}, None)       a valid deferral
    """
    readme = repo / README_REL
    if not readme.is_file():
        return None, None

    text = strip_code(readme.read_text(encoding="utf-8", errors="replace"))
    total = len(MARKER_ANY_RE.findall(text))
    if total == 0:
        return None, None
    if total > 1:
        return None, (f"{README_REL.as_posix()} contains {total} `execution-methodology` markers; "
                      "keep exactly one")

    wellformed = MARKER_RE.findall(text)
    if len(wellformed) != 1:
        return None, (f"the `execution-methodology` marker in {README_REL.as_posix()} must be one "
                      "single-line JSON object")
    try:
        parsed = json.loads(wellformed[0])
    except json.JSONDecodeError as exc:
        return None, (f"the `execution-methodology` marker in {README_REL.as_posix()} is not valid "
                      f"JSON: {exc.msg}")

    if not isinstance(parsed, dict) or parsed.get("mode") != DEFER_MODE:
        return None, (f"the `execution-methodology` marker in {README_REL.as_posix()} must declare "
                      f'`"mode":"{DEFER_MODE}"`')
    reason = parsed.get("reason")
    if not isinstance(reason, str) or not reason.strip():
        return None, (f"the deferral in {README_REL.as_posix()} has no reason — a deferral without "
                      "one is not a decision, so this repository counts as unadopted")
    stamp = parsed.get("date")
    if not isinstance(stamp, str) or not re.fullmatch(r"\d{4}-\d{2}-\d{2}", stamp):
        return None, (f"the deferral in {README_REL.as_posix()} has no `\"date\":\"YYYY-MM-DD\"` — "
                      "without one a deferral cannot age, and counts as unadopted")
    try:
        date.fromisoformat(stamp)
    except ValueError:
        return None, (f"the deferral in {README_REL.as_posix()} has date {stamp!r}, which is not a "
                      "real calendar date")
    return {"reason": reason.strip(), "date": stamp}, None


def adoption_check(repo: Path) -> int:
    """Report one repository's adoption state at session start. ALWAYS returns 0.

    This informs; it never blocks and it never writes. `--check` is the mode that fails a gate, and
    its behaviour is deliberately untouched. Four states, and only three of them say anything:

      adopted and current   silence
      adopted but stale     a warning naming the file and the re-render command
      deliberately deferred one quiet line, with the reason and how long it has been deferred
      unadopted             a warning naming both ways out — adopt, or record a deferral

    Output follows the `AGENT CONTEXT:` head-plus-bullets convention that check_github.py and
    check_toolchain.py already emit into this same session hook, so the lines read as one voice.
    """
    head = f"AGENT CONTEXT: execution methodology v{METHODOLOGY_VERSION}"
    adopt_cmd = f"python3 {Path(__file__).resolve()} --repo {repo}"

    try:
        body = source_text()
        stamp = rendered_date(None)
        overlay = read_overlay(repo)
    except MethodologyError as e:
        # A broken toolchain is worth one line, but never a failed session.
        print(f"{head} could not be evaluated for this repository.")
        print(f"  - [warn] {e}")
        return 0

    target = repo / TARGET_REL
    rel = TARGET_REL.as_posix()
    current = target.read_text(encoding="utf-8", errors="replace") if target.is_file() else None

    # 1. adopted and current — say nothing at all.
    if current is not None and is_ours(current) and current == render(body, stamp, overlay):
        return 0

    # 2. adopted but stale. An unmanaged hand-written file is also "exists but does not match", and
    #    the re-render refuses to clobber it, so it gets the instruction that actually works.
    if current is not None:
        print(f"{head} is rendered into this repository but out of date.")
        if not is_ours(current):
            print(f"  - [warn] {rel} was not generated by this script and does not match the source")
            print(f"  Move it aside, then re-render: `{adopt_cmd}`")
        else:
            print(f"  - [warn] {rel} no longer matches the methodology source")
            print(f"  Re-render: `{adopt_cmd}`")
        return 0

    decision, problem = read_deferral(repo)

    # 3. deliberately deferred — one quiet line, carrying its own age.
    if decision is not None:
        age = (datetime.now(timezone.utc).date() - date.fromisoformat(decision["date"])).days
        print(f"{head} is deliberately deferred here since {decision['date']} "
              f"({age} day{'' if age == 1 else 's'}) — {decision['reason']}")
        return 0

    # 4. unadopted, including a marker that does not qualify as a decision.
    print(f"{head} has not been adopted by this repository.")
    print(f"  - [warn] {problem}" if problem
          else f"  - [warn] no {rel}, and no deferral decision recorded")
    print(f"  Adopt it deliberately — `{adopt_cmd}` renders it and prints the route row to paste.")
    print(f"  Or record a deferral in {README_REL.as_posix()}:")
    print(f"    {DEFERRAL_EXAMPLE}")
    print("  Adoption is never automatic: nothing here will render into this repository for you.")
    return 0


def show_info(repo: Path | None) -> int:
    try:
        body = source_text()
        date = rendered_date(None)
    except MethodologyError as e:
        print(e, file=sys.stderr)
        return 2
    headings = [ln[3:].strip() for ln in body.splitlines() if ln.startswith("## ")]
    print(f"{'source':<10}  {SOURCE}")
    print(f"{'version':<10}  {METHODOLOGY_VERSION}")
    print(f"{'rendered':<10}  {date}  (from source mtime)")
    print(f"{'words':<10}  {len(body.split())}")
    print(f"{'stages':<10}  {', '.join(headings) if headings else '-'}")
    if repo is None:
        return 0
    target = repo / TARGET_REL
    overlay = repo / OVERLAY_REL
    state = "absent"
    if target.is_file():
        text = target.read_text(encoding="utf-8", errors="replace")
        found = MARKER_RE.findall(text)
        if not is_ours(text):
            state = "unmanaged"
        elif found:
            try:
                state = f"v{json.loads(found[0]).get('v', '?')}"
            except json.JSONDecodeError:
                state = "malformed marker"
        else:
            state = "no marker"
    print(f"{'target':<10}  {target}  [{state}]")
    print(f"{'overlay':<10}  {overlay}  [{'present' if overlay.is_file() else 'absent'}]")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=None, help="the repository to render the methodology into")
    ap.add_argument("--check", action="store_true", help="exit 1 when the rendered copy is stale")
    ap.add_argument("--adoption-check", action="store_true", dest="adoption",
                    help="report this repo's adoption state for a session hook; always exits 0")
    ap.add_argument("--list", action="store_true", dest="show",
                    help="print the source, version and rendered date")
    ap.add_argument("--rendered", default=None, metavar="YYYY-MM-DD",
                    help="stamp this date instead of the source's mtime")
    args = ap.parse_args()

    repo = Path(args.repo).resolve() if args.repo else None
    if repo and not repo.is_dir():
        # Silent for the session-hook mode: a path that is not there is not a finding to shout at
        # the start of every session, and this mode's contract is that it never fails anything.
        if args.adoption:
            return 0
        print(f"not a directory: {repo}", file=sys.stderr)
        return 2
    if args.adoption:
        if repo is None:
            print("--repo is required for --adoption-check", file=sys.stderr)
            return 2
        try:
            return adoption_check(repo)
        except Exception as e:  # noqa: BLE001 — a session hook may not die on an unexpected fault
            print(f"AGENT CONTEXT: the execution-methodology adoption check failed to run: {e}")
            return 0
    if args.show:
        return show_info(repo)
    if repo is None:
        print("--repo is required (or use --list)", file=sys.stderr)
        return 2
    return sync(repo, args.check, args.rendered)


if __name__ == "__main__":
    raise SystemExit(main())
