#!/usr/bin/env python3
"""Render one persona pool into the agent formats Claude Code and Codex each require.

Sources in `personas/<name>.md` render to `~/.claude/agents/<name>.md` and, when Codex is
installed, `$CODEX_HOME/agents/<name>.toml`. Routing lives only in their frontmatter; a profile
marked `spawnable: no` (the chief) is read through `routing()` or `--route` and never rendered.
Project personas at `<repo>/docs/agents/personas/` render into the repository's agent trees; one
named like a base persona is skipped with a warning, because overlays of base personas are retired.

Usage:
  sync_personas.py                             render the pool to user level
  sync_personas.py --repo PATH                 also render that repository's personas
  sync_personas.py [--repo PATH] --check       exit 0 current, 1 stale, 2 source error
  sync_personas.py --scope S [--repo PATH] --preview [--json]
  sync_personas.py --list [--format markdown]
  sync_personas.py --route NAME [--variant V]  print one persona's routing as JSON
"""

from __future__ import annotations

import argparse
import json
import os
import re
import secrets
import sys
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
POOL = SKILL / "personas"
CLAUDE_AGENTS = Path.home() / ".claude" / "agents"
# An empty CODEX_HOME is unset; `Path("")` would otherwise be the working directory.
CODEX_ROOT = Path(os.environ.get("CODEX_HOME") or str(Path.home() / ".codex"))
CODEX_AGENTS = CODEX_ROOT / "agents"
GENERATED = "# GENERATED by agent-personas/scripts/sync_personas.py — edit the persona, not this."

BASE_PERSONA_NAMES = frozenset({"advisor", "builder", "chief", "reviewer", "security-reviewer"})

# The read-only roles. Membership is decided here, not by the persona's own `writes:` line, so a
# persona cannot leave the protected set by editing one line about itself; `writes: no` is a claim
# this set checks in both directions.
JUDGING_PERSONA_NAMES = frozenset({"advisor", "reviewer", "security-reviewer"})

# Denied to every judge in the Claude harness, whatever its source says. The allow-list below is the
# policy; this list is the second half of an intersection that must agree with it. `Agent` and
# `SendMessage` are here because dispatching a writer is writing by proxy; `Monitor` and `Bash` run
# arbitrary shell; worktree control and `TaskStop` change state without writing a file.
JUDGE_DENIED_TOOLS = ("Write", "Edit", "NotebookEdit", "Agent", "SendMessage", "Monitor",
                      "EnterWorktree", "ExitWorktree", "TaskStop", "Bash")
# The closed vocabulary a judge's `claude.tools` allow-list may use. A tool nobody has classified
# is a capability granted without an argument, so a new name needs a deliberate edit here.
KNOWN_JUDGE_TOOLS = frozenset({"Read", "Grep", "Glob", "TodoWrite"})
JUDGE_SANDBOX = "read-only"
# Codex has no tool list, so a judge's role file also pins no escalation and no sub-agents. The
# Codex 0.160 role-file schema accepts both (`codex doctor` rejects unknown fields and wrong types);
# their runtime effect on a spawned role has not been observed.
JUDGE_CODEX_PINS = ('approval_policy = "never"', "", "[features]", "multi_agent = false")

# Flat dotted keys, because the format is parsed without PyYAML and a hand-rolled nested parser is
# where silent misreads come from.
CLAUDE_KEYS = {"claude.model": "model", "claude.effort": "effort",
               "claude.tools": "tools", "claude.disallowedTools": "disallowedTools"}
CODEX_KEYS = {"codex.model": "model", "codex.effort": "model_reasoning_effort",
              "codex.sandbox": "sandbox_mode"}
TOP_KEYS = frozenset({"name", "description", "writes", "spawnable"})
VARIANT_KEY = re.compile(r"^variant\.([a-z][a-z0-9-]*)\.(claude|codex)\.(model|effort)$")
# A persona name reaches YAML, TOML and a filename. Anything beyond this pattern (spaces, `#`,
# quotes, capitals) can make a harness read a different name than the one checked here.
NAME = re.compile(r"[a-z][a-z0-9-]*")


class PersonaError(Exception):
    pass


def parse(path: Path) -> tuple[dict, str]:
    """Split `---` frontmatter from the body. Values are plain strings; no type coercion."""
    try:
        text = path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        raise PersonaError(f"{path.name}: unreadable source: {e}") from e
    if not text.startswith("---"):
        raise PersonaError(f"{path.name}: no frontmatter")
    fm, sep, body = text[3:].partition("\n---")
    if not sep:
        raise PersonaError(f"{path.name}: unterminated frontmatter")
    meta: dict[str, str] = {}
    for i, line in enumerate(fm.splitlines(), start=1):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise PersonaError(f"{path.name}:{i}: not a `key: value` line -> {line!r}")
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip().strip('"').strip("'")
    for required in ("name", "description"):
        if not meta.get(required):
            raise PersonaError(f"{path.name}: missing required `{required}`")
    if meta["name"] != path.stem:
        raise PersonaError(f"{path.name}: filename must match persona name `{meta['name']}.md`")
    if not NAME.fullmatch(meta["name"]):
        raise PersonaError(f"{path.name}: persona name {meta['name']!r} must match [a-z][a-z0-9-]*")
    return meta, body.lstrip("\n")


def _tools(value: str | None) -> list[str]:
    return [t.strip() for t in (value or "").split(",") if t.strip()]


def spawnable(meta: dict) -> bool:
    return meta.get("spawnable", "yes") == "yes"


def validate(meta: dict, *, base: bool) -> None:
    """Reject a source that cannot be rendered honestly. Nothing is ever silently corrected."""
    name = meta["name"]
    if meta.get("writes") not in ("yes", "no"):
        raise PersonaError(f"{name}: `writes:` must be `yes` or `no`, not {meta.get('writes')!r}")
    if meta.get("spawnable", "yes") not in ("yes", "no"):
        raise PersonaError(f"{name}: `spawnable:` must be `yes` or `no`")
    if not base:
        return
    unknown = [k for k in meta if k not in TOP_KEYS and k not in CLAUDE_KEYS
               and k not in CODEX_KEYS and not VARIANT_KEY.match(k)]
    if unknown:
        # An unrenderable key reads as policy in the source and reaches the harness as nothing.
        raise PersonaError(f"{name}: unknown frontmatter key(s) {', '.join(unknown)}")
    judging = name in JUDGING_PERSONA_NAMES
    if judging != (meta["writes"] == "no"):
        raise PersonaError(
            f"{name}: declares `writes: {meta['writes']}` but is "
            f"{'' if judging else 'not '}a judging persona; membership is fixed by "
            f"JUDGING_PERSONA_NAMES, so fix the declaration or change the set deliberately")
    if judging:
        check_judge(meta)


def check_judge(meta: dict) -> None:
    """A judge must declare a closed read-only allow-list and a read-only Codex sandbox."""
    name = meta["name"]
    sandbox = meta.get("codex.sandbox")
    if sandbox not in (None, JUDGE_SANDBOX):
        raise PersonaError(f"{name}: a judge requires `codex.sandbox: {JUDGE_SANDBOX}`, "
                           f"not {sandbox!r}")
    declared = _tools(meta.get("claude.tools"))
    if not declared:
        # Without an allow-list the harness grants every tool the deny-list did not think of.
        raise PersonaError(f"{name}: a judge must declare a non-empty `claude.tools` allow-list")
    if "Bash" in declared:
        raise PersonaError(f"{name}: no judging persona may hold Bash; a shell can write anything")
    denied = [t for t in declared if t in JUDGE_DENIED_TOOLS]
    if denied:
        raise PersonaError(f"{name}: `claude.tools` re-grants denied tool(s) {', '.join(denied)}")
    unknown = [t for t in declared if t not in KNOWN_JUDGE_TOOLS]
    if unknown:
        raise PersonaError(f"{name}: `claude.tools` names unclassified tool(s) "
                           f"{', '.join(unknown)}; see KNOWN_JUDGE_TOOLS")
    both = sorted(set(declared) & set(_tools(meta.get("claude.disallowedTools"))))
    if both:
        raise PersonaError(f"{name}: {', '.join(both)} named in both `claude.tools` and "
                           f"`claude.disallowedTools`")


def restricted(meta: dict) -> dict:
    """The judge restriction both renderers apply, so both harnesses get it from one place."""
    if meta.get("name") not in JUDGING_PERSONA_NAMES:
        return meta
    check_judge(meta)
    out = dict(meta)
    extra = [t for t in _tools(meta.get("claude.disallowedTools")) if t not in JUDGE_DENIED_TOOLS]
    out["claude.tools"] = ", ".join(_tools(meta.get("claude.tools")))
    out["claude.disallowedTools"] = ", ".join([*JUDGE_DENIED_TOOLS, *extra])
    out["codex.sandbox"] = JUDGE_SANDBOX
    return out


def routing(meta: dict, variant: str | None = None) -> dict:
    """Model and effort per harness, with a named variant's keys over the defaults.

    A variant overrides only the keys it declares; the rest inherit the persona's default.
    """
    if variant and not any(VARIANT_KEY.match(k) and k.split(".")[1] == variant for k in meta):
        raise PersonaError(f"{meta['name']}: no variant `{variant}`")
    out: dict[str, dict] = {}
    for harness in ("claude", "codex"):
        out[harness] = {}
        for field in ("model", "effort"):
            value = meta.get(f"{harness}.{field}")
            if variant:
                value = meta.get(f"variant.{variant}.{harness}.{field}", value)
            out[harness][field] = value
    return out


def yaml_scalar(v: str) -> str:
    """Quote only when a bare scalar would be misread."""
    return json.dumps(v) if any(c in v for c in ':#{}[]&*!|>%@`"') or v != v.strip() else v


def render_claude(meta: dict, body: str) -> str:
    meta = restricted(meta)
    # The banner is a YAML comment inside the frontmatter; the body is the agent's system prompt.
    lines = ["---", GENERATED, f"name: {yaml_scalar(meta['name'])}",
             f"description: {yaml_scalar(meta['description'])}"]
    lines += [f"{dest}: {yaml_scalar(meta[src])}" for src, dest in CLAUDE_KEYS.items()
              if meta.get(src)]
    return "\n".join(lines + ["---", "", body.rstrip(), ""])


def render_codex(meta: dict, body: str) -> str:
    meta = restricted(meta)
    if "'''" in body:
        # TOML literal strings take no escapes; the delimiter would truncate the instructions.
        raise PersonaError(f"{meta['name']}: body contains ''' which cannot go in a TOML literal")
    out = [GENERATED, f"name = {json.dumps(meta['name'])}",
           f"description = {json.dumps(meta['description'], ensure_ascii=False)}",
           "developer_instructions = '''", body.rstrip(), "'''"]
    out += [f"{dest} = {json.dumps(meta[src])}" for src, dest in CODEX_KEYS.items()
            if meta.get(src)]
    if meta["name"] in JUDGING_PERSONA_NAMES:
        out += JUDGE_CODEX_PINS  # the table header comes last, after every top-level key
    return "\n".join(out) + "\n"


def _all_sources() -> list[Path]:
    return sorted(p for p in POOL.glob("*.md") if p.name.lower() != "readme.md")


def pool_sources() -> list[Path]:
    """The base pool: exactly the BASE_PERSONA_NAMES sources. A missing one is an error.

    Any other source is ignored here and reported by retired_sources(): an installed skill keeps
    the v5.1 sources until `install.sh --retire-v5`, and they must not stop the v6 pool rendering.
    """
    sources = [p for p in _all_sources() if p.stem in BASE_PERSONA_NAMES]
    missing = BASE_PERSONA_NAMES - {p.stem for p in sources}
    if missing:
        raise PersonaError(
            f"base persona pool must hold {', '.join(sorted(BASE_PERSONA_NAMES))} "
            f"(missing: {', '.join(sorted(missing))})")
    return sources


def retired_sources() -> list[Path]:
    """Pool sources outside BASE_PERSONA_NAMES; never parsed, validated or rendered."""
    return [p for p in _all_sources() if p.stem not in BASE_PERSONA_NAMES]


def load(name: str) -> tuple[dict, str]:
    """One base persona, parsed and validated; the driver's entry point for routing."""
    if name not in BASE_PERSONA_NAMES:
        raise PersonaError(f"unknown persona `{name}`")
    meta, body = parse(POOL / f"{name}.md")
    validate(meta, base=True)
    return meta, body


def codex_present() -> bool:
    """Render Codex agents only where Codex lives, rather than creating a tree nothing reads."""
    return CODEX_ROOT.is_dir()


# ---- safe commit: atomic, no-follow writes beneath roots frozen before the first mutation ----

def _open_directory_nofollow(path: Path, *, create: bool) -> int:
    """Open an absolute directory one component at a time without following symlinks."""
    nofollow = getattr(os, "O_NOFOLLOW", None)
    if nofollow is None:
        raise PersonaError("this platform cannot commit safely: O_NOFOLLOW is unavailable")
    flags = os.O_RDONLY | os.O_DIRECTORY | nofollow
    current = os.open(path.anchor, flags)
    try:
        for component in path.parts[1:]:
            try:
                child = os.open(component, flags, dir_fd=current)
            except FileNotFoundError:
                if not create:
                    raise
                try:
                    os.mkdir(component, mode=0o777, dir_fd=current)
                except FileExistsError:
                    pass  # lost a creation race; the no-follow open decides what appeared
                child = os.open(component, flags, dir_fd=current)
            os.close(current)
            current = child
        return current
    except BaseException:
        os.close(current)
        raise


def _open_commit_root(path: Path, *, create: bool) -> int:
    try:
        return _open_directory_nofollow(path, create=create)
    except OSError as e:
        raise PersonaError(f"unsafe generated target root {path}: it changed or contains a "
                           f"symlink at commit time") from e


def _assert_commit_root_unchanged(path: Path, held_fd: int) -> None:
    fresh_fd = _open_commit_root(path, create=False)
    try:
        held, fresh = os.fstat(held_fd), os.fstat(fresh_fd)
        if (held.st_dev, held.st_ino) != (fresh.st_dev, fresh.st_ino):
            raise PersonaError(f"unsafe generated target root {path}: it changed during commit")
    finally:
        os.close(fresh_fd)


def _atomic_write_at(directory_fd: int, name: str, content: str) -> None:
    payload = memoryview(content.encode("utf-8"))
    temp_name = f".{name}.tmp-{os.getpid()}-{secrets.token_hex(8)}"
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW
    temp_fd = os.open(temp_name, flags, 0o666, dir_fd=directory_fd)
    temp_exists = True
    try:
        while payload:
            payload = payload[os.write(temp_fd, payload):]
        os.fsync(temp_fd)
        os.close(temp_fd)
        temp_fd = -1
        os.replace(temp_name, name, src_dir_fd=directory_fd, dst_dir_fd=directory_fd)
        temp_exists = False
    finally:
        if temp_fd >= 0:
            os.close(temp_fd)
        if temp_exists:
            try:
                os.unlink(temp_name, dir_fd=directory_fd)
            except FileNotFoundError:
                pass


def _commit_operations(operations: list[dict], content: dict[str, str],
                       frozen_roots: dict[Path, Path]) -> None:
    """Apply operations as direct children of roots opened before the first mutation."""
    descriptors: dict[Path, int] = {}
    try:
        for op in operations:
            path = Path(op["path"])
            root = path.parent.absolute()
            if root not in frozen_roots or path.name in {"", ".", ".."}:
                raise PersonaError(f"unsafe generated target {path}: outside generated roots")
            if root not in descriptors:
                descriptors[root] = _open_commit_root(frozen_roots[root], create=True)
        for op in operations:
            path = Path(op["path"])
            root = path.parent.absolute()
            if op["action"] == "delete":
                os.unlink(path.name, dir_fd=descriptors[root])
            else:
                _atomic_write_at(descriptors[root], path.name, content[op["path"]])
            _assert_commit_root_unchanged(frozen_roots[root], descriptors[root])
    except OSError as e:
        raise PersonaError(f"generated persona commit failed safely: {e}") from e
    finally:
        for fd in descriptors.values():
            os.close(fd)


def _safe_target(path: Path, root: Path) -> Path:
    """Return the canonical target after rejecting escapes and symlinked components."""
    absolute, root_abs = path.absolute(), root.absolute()
    root_resolved = root_abs.resolve()
    try:
        absolute.resolve(strict=False).relative_to(root_resolved)
        relative = absolute.relative_to(root_abs)
    except ValueError as e:
        raise PersonaError(f"unsafe generated target {absolute}: outside {root_resolved}") from e
    current = root_abs
    for component in (None, *relative.parts):
        current = current / component if component else current
        if current.is_symlink():
            raise PersonaError(f"unsafe generated target {absolute}: symlink at {current}")
    return root_resolved / relative


def _operation_plan(plan: list[tuple[Path, str]], prune_dirs: list[Path],
                    expected: set[Path]) -> list[dict]:
    """Compare the rendered plan with disk; prune only files carrying the GENERATED marker."""
    operations = []
    for path, content in plan:
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current != content:
            operations.append({"action": "create" if current is None else "update",
                               "path": str(path.absolute())})
    for directory in prune_dirs:
        if not directory.is_dir():
            continue
        for path in sorted([*directory.glob("*.md"), *directory.glob("*.toml")]):
            if path.resolve() in expected:
                continue
            try:
                managed = GENERATED in path.read_text(encoding="utf-8", errors="replace")
            except OSError:
                continue
            if managed:
                operations.append({"action": "delete", "path": str(path.absolute())})
    return operations


def _root_for(path: Path, repo: Path | None) -> Path:
    """The authority a generated path must stay beneath: the repository, Codex home, or home."""
    if repo and (path == repo or repo in path.parents):
        return repo
    return CODEX_ROOT if path == CODEX_ROOT or CODEX_ROOT in path.parents else Path.home()


def _scope_for(repo: Path | None, check: bool, scope: str | None) -> str:
    if scope is None:
        return "global" if repo is None else ("project" if check else "all")
    if scope in ("project", "all") and repo is None:
        raise PersonaError(f"--scope {scope} requires --repo PATH")
    if scope == "global" and repo is not None:
        raise PersonaError("--scope global forbids --repo PATH")
    return scope


def build(repo: Path | None, scope: str):
    """Phase A: parse, validate and render everything into a plan. Nothing is written here."""
    findings: list[str] = []
    warnings: list[str] = []
    plan: list[tuple[Path, str]] = []
    expected: set[Path] = set()

    def add(path: Path, render, meta: dict, body: str) -> None:
        expected.add(path.resolve())
        try:
            plan.append((path, render(meta, body)))
        except PersonaError as e:
            findings.append(str(e))

    include_global = scope in ("global", "all")
    for src in retired_sources():
        warnings.append(f"retired persona source {src.stem} ({src}); nothing is rendered from it — "
                        f"run install.sh --retire-v5")
        # Its earlier render is kept, not pruned: v5.1 files go only through --retire-v5, which
        # removes the source and the render together.
        if include_global:
            expected.update({(CLAUDE_AGENTS / f"{src.stem}.md").resolve(),
                             (CODEX_AGENTS / f"{src.stem}.toml").resolve()})
    for src in pool_sources():
        try:
            meta, body = parse(src)
            validate(meta, base=True)
        except PersonaError as e:
            # Still expected, so a broken source is not also reported as an orphan; this run
            # exits 2 regardless. A valid non-spawnable profile is not expected, so a stale
            # rendering of it is pruned.
            expected.update({(CLAUDE_AGENTS / f"{src.stem}.md").resolve(),
                             (CODEX_AGENTS / f"{src.stem}.toml").resolve()})
            findings.append(str(e))
            continue
        if include_global and spawnable(meta):
            add(CLAUDE_AGENTS / f"{meta['name']}.md", render_claude, meta, body)
            if codex_present():
                add(CODEX_AGENTS / f"{meta['name']}.toml", render_codex, meta, body)

    targets = ([CLAUDE_AGENTS] + ([CODEX_AGENTS] if codex_present() else [])
               if include_global else [])
    if scope in ("project", "all"):
        claude_dir, codex_dir = repo / ".claude" / "agents", repo / ".codex" / "agents"
        targets += [claude_dir, codex_dir]
        sources_dir = repo / "docs" / "agents" / "personas"
        for src in sorted(sources_dir.glob("*.md")) if sources_dir.is_dir() else []:
            if src.name.lower() == "readme.md":
                continue
            if src.stem.lower() in BASE_PERSONA_NAMES:
                warnings.append(f"{src}: overlays of base personas are retired, so this file is "
                                f"skipped; migrate its direction into the project's docs or give "
                                f"it a name of its own")
                continue
            try:
                meta, body = parse(src)
                validate(meta, base=False)
            except PersonaError as e:
                expected.update({(claude_dir / f"{src.stem}.md").resolve(),
                                 (codex_dir / f"{src.stem}.toml").resolve()})
                findings.append(f"project {e}")
                continue
            if not spawnable(meta):
                continue
            # A project persona's tool policy is its own declaration, rendered as written; the
            # derived judge restriction covers the base judging set only.
            add(claude_dir / f"{meta['name']}.md", render_claude, meta, body)
            add(codex_dir / f"{meta['name']}.toml", render_codex, meta, body)
    return plan, expected, targets, findings, warnings


def _json_plan(scope: str, operations: list, findings: list[str], warnings: list[str]) -> str:
    return json.dumps({
        "schema_version": 1, "scope": scope, "operations": operations,
        "findings": [{"code": "persona_invalid", "severity": "error", "message": f}
                     for f in findings]
        + [{"code": "persona_warning", "severity": "warning", "message": w} for w in warnings],
    }, sort_keys=True)


def sync(repo: Path | None, check: bool, *, scope: str | None = None,
         preview: bool = False, json_output: bool = False) -> int:
    selected = scope or "invalid"
    operations: list[dict] = []
    findings: list[str] = []
    warnings: list[str] = []
    plan: list[tuple[Path, str]] = []
    frozen: dict[Path, Path] = {}
    try:
        selected = _scope_for(repo, check, scope)
        plan, expected, targets, findings, warnings = build(repo, selected)
        # Phase B: compare once. Preview, check and apply all consume this operation list, and
        # every finding is collected before anything is written.
        for path, _ in plan:
            _safe_target(path, _root_for(path, repo))
        frozen = {d.absolute(): _safe_target(d, _root_for(d, repo)) for d in targets}
        operations = _operation_plan(plan, targets, expected)
    except (OSError, UnicodeDecodeError, PersonaError) as e:
        findings.append(str(e))

    if json_output:
        print(_json_plan(selected, [] if findings else operations, findings, warnings))
        return 2 if findings else (1 if check and operations else 0)

    for w in warnings:
        print(f"  WARNING {w}", file=sys.stderr)
    if preview:
        print(f"personas: {len(operations)} planned operation(s) ({selected})")
        for op in operations:
            print(f"  {op['action']:<6} {op['path']}")
    elif check or findings:
        # A validation failure does not suppress the staleness comparison.
        if operations:
            print(f"  STALE — {len(operations)} generated file(s) do not match the source:")
            for op in operations:
                print(f"    {op['path']}")
        elif not findings:
            print("  in sync")
    if findings:
        for f in findings:
            print(f"  ERROR {f}", file=sys.stderr)
        if not (preview or check):
            print("  nothing was written: a run that reports a failure must not also change what "
                  "the harness loads.", file=sys.stderr)
        return 2
    if preview or check:
        return 1 if check and operations else 0

    content = {str(path.absolute()): text for path, text in plan}
    try:
        _commit_operations(operations, content, frozen)
    except PersonaError as e:
        print(f"  ERROR {e}", file=sys.stderr)
        return 2
    print(f"personas: {len(BASE_PERSONA_NAMES)} in the pool ({selected})")
    for op in operations:
        verb = "removed" if op["action"] == "delete" else "wrote  "
        print(f"  {verb} {op['path']}")
    if not operations:
        print("  already up to date")
    return 0


def show_roster(output_format: str = "text") -> int:
    headings = ("persona", "spawnable", "writes", "claude", "effort", "codex", "effort")
    try:
        rows = []
        for src in pool_sources():
            m, _ = parse(src)
            rows.append((m["name"], m.get("spawnable", "yes"), m.get("writes", "?"),
                         m.get("claude.model", "-"), m.get("claude.effort", "-"),
                         m.get("codex.model", "-"), m.get("codex.effort", "-")))
    except PersonaError as e:
        print(e, file=sys.stderr)
        return 2
    if output_format == "markdown":
        print("| " + " | ".join(h.capitalize() for h in headings) + " |")
        print("|" + "---|" * len(headings))
        for row in rows:
            print("| " + " | ".join(row) + " |")
        return 0
    widths = [max(len(h), *(len(r[i]) for r in rows)) for i, h in enumerate(headings)]
    for row in (headings, *rows):
        print("  ".join(f"{v:<{widths[i]}}" for i, v in enumerate(row)).rstrip())
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=None, help="also render this repository's personas")
    ap.add_argument("--check", action="store_true", help="exit 1 when generated output is stale")
    ap.add_argument("--scope", choices=("project", "global", "all"), default=None)
    ap.add_argument("--preview", action="store_true", help="report the operation plan only")
    ap.add_argument("--json", action="store_true", dest="json_output",
                    help="emit the preview plan as one JSON object")
    ap.add_argument("--list", action="store_true", dest="show", help="print the pool")
    ap.add_argument("--format", choices=("text", "markdown"), default=None)
    ap.add_argument("--route", default=None, help="print one persona's routing as JSON")
    ap.add_argument("--variant", default=None, help="with --route: a named variant")
    args = ap.parse_args()

    reconcile = args.scope or args.preview or args.json_output or args.check or args.repo
    if args.format and not args.show:
        ap.error("--format requires --list")
    if args.variant and not args.route:
        ap.error("--variant requires --route")
    if ((args.show or args.route) and reconcile) or (args.show and args.route):
        ap.error("--list and --route stand alone")
    if args.json_output and not args.preview:
        ap.error("--json requires --preview")
    if args.show:
        return show_roster(args.format or "text")
    if args.route:
        try:
            meta, _ = load(args.route)
            print(json.dumps(routing(meta, args.variant), sort_keys=True))
            return 0
        except (OSError, PersonaError) as e:
            print(f"  ERROR {e}", file=sys.stderr)
            return 2
    repo = Path(args.repo).resolve() if args.repo else None
    if repo and not repo.is_dir():
        print(f"not a directory: {repo}", file=sys.stderr)
        return 2
    return sync(repo, args.check, scope=args.scope, preview=args.preview,
                json_output=args.json_output)


if __name__ == "__main__":
    raise SystemExit(main())
