#!/usr/bin/env python3
"""Render one persona pool into the formats Claude Code and Codex each require.

A persona is authored once, harness-neutral, in `personas/<name>.md`. This renders it to:

  ~/.claude/agents/<name>.md      YAML frontmatter + markdown body as the system prompt
  ~/.codex/agents/<name>.toml     TOML with developer_instructions

Generation is not a convenience. Claude Code's project-level agents *override* a same-named user
agent wholesale, so "the base persona plus a project-specific instruction" cannot be expressed by
putting files in two places — the project file would silently replace the base. Merging has to
happen before the harness sees it.

Per-project use: an overlay at `<repo>/docs/agents/personas/<name>.md` is appended to the base
persona and the merged result written into that repo's `.claude/agents/` and `.codex/agents/`.
A project only needs files for personas it actually specialises; the rest resolve to the user-level
copies.

Usage:
  sync_personas.py                       # render the pool to user level
  sync_personas.py --repo PATH           # also render that repo's overlays
  sync_personas.py --repo PATH --check   # exit 1 if generated output is stale (for gates)
  sync_personas.py --list                # show the roster with model and effort
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
POOL = SKILL / "personas"
CLAUDE_AGENTS = Path.home() / ".claude" / "agents"
CODEX_AGENTS = Path.home() / ".codex" / "agents"
BASE_PERSONA_NAMES = frozenset({
    "acceptance",
    "architect",
    "chief-of-staff",
    "contract-architect",
    "developer",
    "docs-steward",
    "planner",
    "product-steward",
    "reviewer",
    "scout",
    "security-validator",
    "senior-developer",
    "test-judge",
})


def codex_present() -> bool:
    """Only render Codex agents where Codex actually lives.

    Rendering unconditionally creates a ~/.codex tree on a machine that has no Codex — files nothing
    will ever read, in a directory the user did not ask for. Absence of ~/.codex is the only
    reliable signal available here.
    """
    return (Path.home() / ".codex").is_dir()

GENERATED = "# GENERATED by agent-personas/scripts/sync_personas.py — edit the persona, not this."

# Keys read from a persona's frontmatter. Flat and dotted rather than nested, because the format has
# to be parsed without PyYAML (not in the stdlib) and a hand-rolled nested parser is where silent
# misreads come from.
CLAUDE_KEYS = {"claude.model": "model", "claude.effort": "effort",
               "claude.tools": "tools", "claude.disallowedTools": "disallowedTools"}
CODEX_KEYS = {"codex.model": "model", "codex.effort": "model_reasoning_effort",
              "codex.sandbox": "sandbox_mode"}


class PersonaError(Exception):
    pass


def pool_sources() -> list[Path]:
    """Return the canonical base pool or reject global specialist leakage."""
    sources = sorted(
        p for p in POOL.glob("*.md") if p.name.lower() != "readme.md"
    )
    if not sources:
        raise PersonaError(f"no personas in {POOL}")
    actual_names = {p.stem for p in sources}
    if actual_names != BASE_PERSONA_NAMES:
        details = []
        missing = sorted(BASE_PERSONA_NAMES - actual_names)
        unexpected = sorted(actual_names - BASE_PERSONA_NAMES)
        if missing:
            details.append("missing: " + ", ".join(missing))
        if unexpected:
            details.append("unexpected: " + ", ".join(unexpected))
        raise PersonaError(
            "base persona pool must contain exactly the canonical 13 ("
            + "; ".join(details)
            + ")"
        )
    return sources


def parse(path: Path) -> tuple[dict, str]:
    """Split `---` frontmatter from the body. Values are plain strings; no type coercion."""
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise PersonaError(f"{path.name}: no frontmatter")
    _, _, rest = text.partition("---")
    fm, sep, body = rest.partition("\n---")
    if not sep:
        raise PersonaError(f"{path.name}: unterminated frontmatter")

    meta: dict[str, str] = {}
    for i, line in enumerate(fm.splitlines(), start=2):
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if ":" not in line:
            raise PersonaError(f"{path.name}:{i}: not a `key: value` line -> {line!r}")
        k, _, v = line.partition(":")
        meta[k.strip()] = v.strip().strip('"').strip("'")

    for required in ("name", "description"):
        if not meta.get(required):
            raise PersonaError(f"{path.name}: missing required `{required}`")
    if meta["name"] != path.stem:
        raise PersonaError(
            f"{path.name}: filename must match persona name `{meta['name']}.md`"
        )
    return meta, body.lstrip("\n")


def yaml_scalar(v: str) -> str:
    """Quote only when a bare scalar would be misread. Keeps generated frontmatter readable."""
    return f'"{v}"' if any(c in v for c in ':#{}[]&*!|>%@`"') or v != v.strip() else v


def render_claude(meta: dict, body: str) -> str:
    # The banner goes inside the frontmatter as a YAML comment, never into the body. The body IS the
    # agent's system prompt, so a note addressed to a human reader — "edit the persona, not this" —
    # would sit there as a stray instruction the agent has to interpret.
    lines = ["---", GENERATED, f"name: {meta['name']}",
             f"description: {yaml_scalar(meta['description'])}"]
    for src, dest in CLAUDE_KEYS.items():
        if meta.get(src):
            lines.append(f"{dest}: {yaml_scalar(meta[src])}")
    lines += ["---", "", body.rstrip(), ""]
    return "\n".join(lines)


def render_codex(meta: dict, body: str) -> str:
    if "'''" in body:
        # TOML literal strings take no escapes, which is exactly why they are safe for prose. A body
        # containing the delimiter would silently truncate the instructions.
        raise PersonaError(f"{meta['name']}: body contains ''' which cannot go in a TOML literal")
    out = [GENERATED,
           f'name = "{meta["name"]}"',
           f'description = "{meta["description"]}"',
           "developer_instructions = '''",
           body.rstrip(),
           "'''", ""]
    for src, dest in CODEX_KEYS.items():
        if meta.get(src):
            out.append(f'{dest} = "{meta[src]}"')
    return "\n".join(out) + "\n"


def overlay_body(base: str, extra: str, project: str) -> str:
    """Base persona, then the project's additions. Order matters: the general rule is established
    first, so a project instruction reads as a refinement rather than a replacement."""
    return (f"{base.rstrip()}\n\n"
            f"## Project-specific direction — {project}\n\n"
            f"{extra.strip()}\n")


def prune(dirs: list[Path], expected: set[Path], check: bool,
          removed: list, stale: list, *, require_sourced: bool = False) -> None:
    """Delete generated agents whose persona no longer exists.

    Without this, renaming or removing a persona leaves its rendered files behind and they stay
    dispatchable — an agent definition pointing at a role the pool no longer defines, with no
    source to fix. Splitting one persona into two is exactly when this bites.

    Only files carrying our banner are touched. Hand-written agents living in the same directory
    are somebody's work and must survive.
    """
    for d in dirs:
        if not d.is_dir():
            continue
        for f in sorted(list(d.glob("*.md")) + list(d.glob("*.toml"))):
            if f.resolve() in expected:
                continue
            try:
                if GENERATED not in f.read_text(encoding="utf-8", errors="replace"):
                    if check and require_sourced:
                        stale.append(f"{f} (unmanaged — no persona source)")
                    continue          # preserve hand-written files; the check reports them
            except OSError:
                continue
            if check:
                stale.append(f"{f} (orphaned — no persona source)")
            else:
                f.unlink()
                removed.append(str(f))


def write(path: Path, content: str, check: bool, changed: list, stale: list) -> None:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == content:
        return
    if check:
        stale.append(str(path))
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    changed.append(str(path))


def sync(repo: Path | None, check: bool) -> int:
    if not POOL.is_dir():
        print(f"no persona pool at {POOL}", file=sys.stderr)
        return 2
    try:
        sources = pool_sources()
    except PersonaError as e:
        print(e, file=sys.stderr)
        return 2

    changed: list[str] = []
    removed: list[str] = []
    stale: list[str] = []
    expected: set[Path] = set()
    overlays_dir = (repo / "docs" / "agents" / "personas") if repo else None
    project_specific = 0
    check_global = not (check and repo is not None)

    def expect(p: Path) -> Path:
        expected.add(p.resolve())
        return p

    for src in sources:
        try:
            meta, body = parse(src)
        except PersonaError as e:
            print(f"  ERROR {e}", file=sys.stderr)
            return 2
        name = meta["name"]

        if check_global:
            write(expect(CLAUDE_AGENTS / f"{name}.md"), render_claude(meta, body),
                  check, changed, stale)
            if codex_present():
                write(expect(CODEX_AGENTS / f"{name}.toml"), render_codex(meta, body),
                      check, changed, stale)

        if overlays_dir and (overlays_dir / f"{name}.md").is_file():
            try:
                o_meta, o_body = parse(overlays_dir / f"{name}.md")
            except PersonaError as e:
                print(f"  ERROR overlay {e}", file=sys.stderr)
                return 2
            merged = overlay_body(body, o_body, repo.name)
            # An overlay may retune model/effort for this project; anything it omits inherits.
            m = {**meta, **{k: v for k, v in o_meta.items() if v}}
            write(expect(repo / ".claude" / "agents" / f"{name}.md"), render_claude(m, merged),
                  check, changed, stale)
            write(expect(repo / ".codex" / "agents" / f"{name}.toml"), render_codex(m, merged),
                  check, changed, stale)
            project_specific += 1

    # A specialist the factory produced for this repo only: an overlay with no base persona behind
    # it. It is a whole persona, so it renders from itself.
    if overlays_dir and overlays_dir.is_dir():
        base_names = {parse(s)[0]["name"] for s in sources}
        for ov in sorted(overlays_dir.glob("*.md")):
            if ov.name.lower() == "readme.md":
                continue
            try:
                meta, body = parse(ov)
            except PersonaError as e:
                print(f"  ERROR overlay {e}", file=sys.stderr)
                return 2
            if meta["name"] in base_names:
                continue
            write(expect(repo / ".claude" / "agents" / f"{meta['name']}.md"), render_claude(meta, body),
                  check, changed, stale)
            write(expect(repo / ".codex" / "agents" / f"{meta['name']}.toml"),
                  render_codex(meta, body), check, changed, stale)
            project_specific += 1

    global_targets = []
    if check_global:
        global_targets = [CLAUDE_AGENTS] + ([CODEX_AGENTS] if codex_present() else [])
    prune(global_targets, expected, check, removed, stale)
    if repo:
        project_targets = [repo / ".claude" / "agents", repo / ".codex" / "agents"]
        prune(project_targets, expected, check, removed, stale, require_sourced=True)

    print(f"personas: {len(sources)} in the pool"
          + (f", {project_specific} project persona source"
             f"{'' if project_specific == 1 else 's'} for {repo.name}" if repo else ""))
    if check:
        if stale:
            print(f"  STALE — {len(stale)} generated file(s) do not match the persona source:")
            for s in stale[:12]:
                print(f"    {s}")
            print("  run: sync_personas.py" + (f" --repo {repo}" if repo else ""))
            return 1
        print("  in sync")
        return 0
    for c in changed:
        print(f"  wrote   {c}")
    for r in removed:
        print(f"  removed {r}  (orphaned — persona no longer in the pool)")
    if not changed and not removed:
        print("  already up to date")
    return 0


def show_roster() -> int:
    rows = []
    try:
        sources = pool_sources()
        for src in sources:
            m, _ = parse(src)
            rows.append((m["name"], m.get("writes", "?"), m.get("claude.model", "-"),
                         m.get("claude.effort", "-"), m.get("codex.model", "-")))
    except PersonaError as e:
        print(e, file=sys.stderr)
        return 2
    w = max((len(r[0]) for r in rows), default=4)
    print(f"{'persona':<{w}}  {'writes':<6} {'claude':<10} {'effort':<7} codex")
    for n, wr, cm, ce, xm in rows:
        print(f"{n:<{w}}  {wr:<6} {cm:<10} {ce:<7} {xm}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--repo", default=None, help="also render this repository's overlays")
    ap.add_argument("--check", action="store_true", help="exit 1 when generated output is stale")
    ap.add_argument("--list", action="store_true", dest="show", help="print the roster")
    args = ap.parse_args()

    if args.show:
        return show_roster()
    repo = Path(args.repo).resolve() if args.repo else None
    if repo and not repo.is_dir():
        print(f"not a directory: {repo}", file=sys.stderr)
        return 2
    return sync(repo, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
