#!/usr/bin/env bash
# Install the v7 methodology into ~/.claude and $CODEX_HOME (default ~/.codex; skipped when absent).
#
#   ./install.sh               install or update; a second run changes nothing
#   ./install.sh --dry-run     print every action, write nothing (combines with the two below)
#   ./install.sh --uninstall   remove what this script installs; restore the newest global-file backup
#   ./install.sh --retire-v5   install, then delete the named v5.1 and v6 leftovers; report the rest
#
set -uo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE="$HOME/.claude"
CODEX="${CODEX_HOME:-$HOME/.codex}"
SKILL=execution-methodology
MODE=install DRY=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY=1 ;;
    --uninstall) MODE=uninstall ;;
    --retire-v5) MODE=retire ;;
    -h|--help) sed -n '2,8p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 64 ;;   # EX_USAGE: nothing was changed
  esac
done

FAILURES=""
say()  { printf '  %s\n' "$1"; }
fail() { FAILURES="${FAILURES}  - $1"$'\n'; printf '  FAILED: %s\n' "$1"; }
step() { local m="$1"; shift; if [ "$DRY" -eq 1 ]; then say "would: $*"; else "$@" && say "$m"; fi; }  # MSG CMD...
STAMP="$(date +%Y%m%d-%H%M%S)"

command -v python3 >/dev/null || { echo "python3 is required" >&2; exit 1; }
PYV=$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')
python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)' ||
  { echo "python3 $PYV found; 3.10 or newer is required" >&2; exit 1; }
echo "methodology installer: $MODE$([ "$DRY" -eq 1 ] && echo ' (dry run: nothing will be written)'), python3 $PYV"
ROOTS=("$CLAUDE")   # an array: a harness home may contain spaces
if [ -d "$CODEX" ]; then ROOTS+=("$CODEX"); else say "no $CODEX: Codex is not installed here, so its side is skipped"; fi
global_of() { if [ "$1" = "$CLAUDE" ]; then echo "$1/CLAUDE.md"; else echo "$1/AGENTS.md"; fi; }
hooks_of()  { if [ "$1" = "$CLAUDE" ]; then echo "$1/settings.json"; else echo "$1/hooks.json"; fi; }

# ── Retire list ─────────────────────────────────────────────────────────────────────────────────
# The one place that names the retired set on purpose; verify.sh's dangling-name scan skips the
# lines between the markers. --retire-v5 deletes exactly these under each harness home:
#   RETIRED_SKILLS   skills/<name>/          RETIRED_HOOKS  hooks/<name>, and their registrations
#   RETIRED_PERSONAS agents/<name>.md|.toml, only when the file carries GENERATED_MARK
#   RETIRED_FILES    paths under skills/; one ending in / is a directory (v7 installs no tests/)
# BEGIN retire-v5 list
RETIRED_SKILLS="methodology-management project-onboarding project-migration project-conformance agent-persona-factory gate-sandbox agent-personas progressive-disclosure graph-navigation"
RETIRED_PERSONAS="acceptance architect chief-of-staff contract-architect developer docs-steward migration-validator planner product-steward scout security-validator senior-developer test-judge advisor builder chief reviewer security-reviewer"
RETIRED_HOOKS="goal-session.sh disclosure-check.sh preflight.sh graphify-query-advisor.py graphify-session-lessons.sh"
GENERATED_MARK="# GENERATED by agent-personas/scripts/sync_personas.py"
RETIRED_FILES="ROUND-GRANTS.tsv methodology.md agents/openai.yaml tests/ scripts/review.py scripts/run_goal.py
scripts/runtime-status.schema.json references/changelog-v1-v2.md references/codex-gate-sandbox.md
references/execution-loop.md references/history-v3-v5.md references/junit-evidence.md references/readme.md
references/specs.md references/task-card.md references/review.md references/escalation.md references/planning.md
references/run.md references/migrate.md references/explainer-template.html"
for n in check_review_budget milestone_seal plan_waves ratio_meter spec_check start_junit_run sync_methodology trace_check validate_card verify_junit weekly_review; do
  RETIRED_FILES="$RETIRED_FILES scripts/$n.py scripts/${n}_selftest.py"
done
# END retire-v5 list
retired_entry() {  # retired_entry REL: print the RETIRED_FILES entry that covers REL, if any
  local e; for e in $RETIRED_FILES; do
    if [ "$1" = "$e" ] || { [ "${e%/}" != "$e" ] && [ "${1#"$e"}" != "$1" ]; }; then echo "$e"; return 0; fi
  done; return 1
}

# ── The skill ────────────────────────────────────────────────────────────────────────────────────
# extras SRC DEST: files DEST has and SRC lacks, ignoring __pycache__ (carried forward, reported).
extras() { [ -d "$2" ] && (cd "$2" && find . \( -type f -o -type l \) -not -path '*/__pycache__/*') |
  sed 's|^\./||' | while IFS= read -r rel; do [ -e "$1/$rel" ] || [ -L "$1/$rel" ] || echo "$rel"; done; }
# Staged beside the old copy and swapped in by rename, so a failed copy leaves the working install
# (whose guard.py every repository's git hooks call) intact. tests/ is not shipped.
install_skill() {  # install_skill ROOT
  local src="$HERE/skills/$SKILL" dest="$1/skills/$SKILL" st="$1/skills/.$SKILL.new" old="$1/skills/.$SKILL.old" rel kept
  kept="$(extras "$src" "$dest")"
  [ -z "$kept" ] || while IFS= read -r rel; do say "kept $dest/$rel (not in this package)"; done <<< "$kept"
  if [ -z "$(diff -rq -x __pycache__ -x tests "$src" "$dest" 2>&1 | grep -vF "Only in $dest")" ]; then
    say "unchanged $dest"; return 0; fi
  [ "$DRY" -eq 1 ] && { say "would: copy $src (without tests/) to $dest"; return 0; }
  rm -rf "$st" "$old" && mkdir -p "$1/skills" && cp -R "$src" "$st" && rm -rf "$st/tests" &&
    find "$st" -name __pycache__ -prune -exec rm -rf {} + && chmod +x "$st"/scripts/* || { rm -rf "$st"; return 1; }
  while IFS= read -r rel; do [ -n "$rel" ] || continue
    mkdir -p "$(dirname "$st/$rel")" && cp -P -p "$dest/$rel" "$st/$rel" || { rm -rf "$st"; return 1; }
  done <<< "$kept"
  if { [ ! -e "$dest" ] || mv "$dest" "$old"; } && mv "$st" "$dest"; then rm -rf "$old"; say "installed $dest"; return 0; fi
  [ -e "$dest" ] || [ ! -e "$old" ] || mv "$old" "$dest"; rm -rf "$st"; return 1
}
# Uninstall removes the files this package ships and the directories that leaves empty; files it
# does not ship (the ones install_skill carries forward) stay, with their directories, and are reported.
uninstall_skill() {  # uninstall_skill ROOT
  local src="$HERE/skills/$SKILL" dest="$1/skills/$SKILL" kept rel
  { [ -e "$dest" ] || [ -L "$dest" ]; } || return 0
  kept="$(extras "$src" "$dest")"
  [ -n "$kept" ] || { step "removed $dest" rm -rf "$dest"; return; }
  if [ "$DRY" -eq 0 ]; then
    (cd "$src" && find . \( -type f -o -type l \) -not -path '*/__pycache__/*') | sed 's|^\./||' |
      while IFS= read -r rel; do rm -f "$dest/$rel" || exit 1; done &&
      find "$dest" -name __pycache__ -prune -exec rm -rf {} + && find "$dest" -depth -type d -empty -delete || return 1
  fi
  say "$([ "$DRY" -eq 1 ] && echo 'would: ')removed this package's files from $dest"
  while IFS= read -r rel; do say "left in place (not in this package): $dest/$rel"; done <<< "$kept"
}

# ── Global instructions ──────────────────────────────────────────────────────────────────────────
install_global() {  # install_global DEST: back up a file that differs, then write global.md
  local dest="$1" bak="$1.bak-$STAMP"
  cmp -s "$HERE/global.md" "$dest" && { say "unchanged $dest"; return 0; }
  [ ! -e "$bak" ] || bak="$bak.$$"
  if [ -e "$dest" ]; then step "backup: $bak" cp -p "$dest" "$bak" || return 1; fi
  { [ "$DRY" -eq 1 ] || mkdir -p "$(dirname "$dest")"; } && step "wrote $dest" cp "$HERE/global.md" "$dest"
}
uninstall_global() {  # remove only an unmodified copy of global.md, then move the newest backup back
  local dest="$1" bak
  if [ -e "$dest" ] && ! cmp -s "$HERE/global.md" "$dest"; then say "left in place (differs from global.md): $dest"; return 0; fi
  if [ -e "$dest" ]; then step "removed $dest" rm -f "$dest" || return 1; fi
  bak="$(ls -1d "$dest".bak-* 2>/dev/null | sort | tail -1)"
  [ -z "$bak" ] || step "restored $dest from $bak" mv "$bak" "$dest"
}

# ── Hook files ───────────────────────────────────────────────────────────────────────────────────
# Edited, never replaced: a file that is not valid JSON or not in the hooks shape is refused; only
# hook items whose command contains a NEEDLE are dropped, the rest keep their index (Codex keys hook
# trust on it). A changed file is backed up first. Nothing is ever registered here: run.sh registers
# the Stop hook per session (S-1 run-security decision).
HOOKS_PY="$(cat <<'PY'
import json, shutil, sys, time
from pathlib import Path
path, dry, needles = Path(sys.argv[1]), sys.argv[2] == "1", sys.argv[3:]
try:
    data = json.loads(path.read_text(encoding="utf-8") or "{}") if path.is_file() else {}
except json.JSONDecodeError as e:
    sys.exit(f"  REFUSED: {path} is not valid JSON ({e}). Fix it by hand, then re-run.")
ev = data.setdefault("hooks", {}) if isinstance(data, dict) else None
if not isinstance(ev, dict) or not all(isinstance(es, list) and all(
        isinstance(e, dict) and isinstance(e.get("hooks", []), list) and all(isinstance(h, dict) for h in e.get("hooks", []))
        for e in es) for es in ev.values()):
    sys.exit(f"  REFUSED: {path} is not in the expected hooks shape. Fix it by hand; nothing changed.")
done = []
for name, entries in list(ev.items()):
    for e in entries:
        gone = [h for h in e.get("hooks", []) if any(n in str(h.get("command", "")) for n in needles)]
        done += [f"unregistered {name}: {h.get('command')}" for h in gone]
        e["hooks"] = [h for h in e.get("hooks", []) if h not in gone] if gone else e.get("hooks")
    ev[name] = [e for e in entries if e.get("hooks") or "hooks" not in e]
    if entries and not ev[name]:
        del ev[name]
for d in done:
    print(f"  {'would: ' if dry else ''}{d} in {path}")
if done and not dry and data == {"hooks": {}}:   # nothing but our entries: the file was ours
    path.unlink()
    print(f"  removed {path}")
elif done and not dry:
    if path.is_file():
        stem = f"{path.name}.bak-{time.strftime('%Y%m%d-%H%M%S')}"
        bak = next(path.with_name(stem + (f".{i}" if i else "")) for i in range(1000)
                   if not path.with_name(stem + (f".{i}" if i else "")).exists())
        shutil.copy2(path, bak)
        print(f"  backup: {bak}")
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    tmp.replace(path)
elif not done:
    print(f"  unchanged {path}")
PY
)"
edit_hooks() {  # edit_hooks ROOT NEEDLE...: drop the hook items whose command holds a NEEDLE
  local r="$1"; shift
  python3 -c "$HOOKS_PY" "$(hooks_of "$r")" "$DRY" "$@"
}

# ── Retire ───────────────────────────────────────────────────────────────────────────────────────
retire() { if [ "$DRY" -eq 1 ]; then say "would delete $1"; else rm -rf "$1" && say "deleted $1" || fail "retire-v5: could not delete $1"; fi; }
retire_root() {  # retire_root ROOT AGENT_EXT
  local r="$1" ext="$2" n e rel seen=" "
  for n in $RETIRED_SKILLS; do { [ -e "$r/skills/$n" ] || [ -L "$r/skills/$n" ]; } && retire "$r/skills/$n"; done
  while IFS= read -r rel; do [ -n "$rel" ] || continue
    if e="$(retired_entry "$rel")"; then
      case "$seen" in *" $e "*) ;; *) seen="$seen$e "; retire "$r/skills/$SKILL/${e%/}" ;; esac
    else say "left in place (not in the retire list): $r/skills/$SKILL/$rel"; fi
  done < <(extras "$HERE/skills/$SKILL" "$r/skills/$SKILL")
  for n in $RETIRED_HOOKS; do [ -e "$r/hooks/$n" ] && retire "$r/hooks/$n"; done
  [ -f "$(hooks_of "$r")" ] && { edit_hooks "$r" $(for n in $RETIRED_HOOKS; do echo "hooks/$n"; done) ||
    fail "retire-v5: $(hooks_of "$r") was not edited"; }
  for n in $RETIRED_PERSONAS; do
    e="$r/agents/$n.$ext"; [ -f "$e" ] || continue
    if grep -qF "$GENERATED_MARK" "$e"; then retire "$e"; else say "kept $e (named in the retire list but not generated)"; fi
  done
  for e in "$r"/skills/* "$r"/hooks/* "$r"/agents/*.md "$r"/agents/*.toml "$r/approved-runtimes"; do
    { [ -e "$e" ] || [ -L "$e" ]; } && [ "$e" != "$r/skills/$SKILL" ] || continue
    n="$(basename "$e")"
    case " $RETIRED_SKILLS $RETIRED_PERSONAS $RETIRED_HOOKS " in *" $n "*|*" ${n%.*} "*) continue ;; esac
    say "left in place (not in the retire list): $e"
  done
}

# ── Run ──────────────────────────────────────────────────────────────────────────────────────────
for r in "${ROOTS[@]}"; do
  echo "$r"
  if [ "$MODE" = uninstall ]; then
    uninstall_global "$(global_of "$r")" || fail "uninstall: $(global_of "$r")"
    uninstall_skill "$r" || fail "uninstall: $r/skills/$SKILL"
    [ "$DRY" -eq 1 ] || rmdir "$r/skills" 2>/dev/null || true   # only when the skill was all it held
    [ ! -f "$(hooks_of "$r")" ] || edit_hooks "$r" "goal.py stop-hook" || fail "uninstall: $(hooks_of "$r")"
  else
    install_global "$(global_of "$r")" || fail "global instructions: $(global_of "$r") was not written"
    install_skill "$r" || fail "skill: $r/skills/$SKILL was not installed"
    # An earlier install registered the Stop hook globally; run.sh owns it now, so drop that entry.
    [ ! -f "$(hooks_of "$r")" ] || edit_hooks "$r" "goal.py stop-hook" || fail "stop hook: $(hooks_of "$r") was not edited"
  fi
done
if [ "$MODE" = retire ]; then
  echo "retire v5.1 and v6 leftovers"
  if [ -n "$FAILURES" ]; then say "SKIPPED: an install step above failed, so nothing was retired"
  else for r in "${ROOTS[@]}"; do if [ "$r" = "$CLAUDE" ]; then retire_root "$r" md; else retire_root "$r" toml; fi; done; fi
fi
if [ -n "$FAILURES" ]; then printf '\n%s FAILED; these steps did not complete:\n%s' "$MODE" "$FAILURES" >&2; exit 1; fi
[ "$MODE" = uninstall ] || say "next: ./verify.sh; unattended runs register their Stop hook per session (scripts/run.sh)"
exit 0
